# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT

# GENERATED by ggen from templates/test_helper.exs.tmpl -- edit the template, not this file.
#
# GraphLaw pin: 26.9.29 (ABI 1).
#
# Tests tagged `:wasm` execute the REAL pinned GraphLaw wasm engine. When the engine is
# absent (`mix ash_graphlaw.vendor` not yet run) or fails the digest pin, those tests are
# EXCLUDED with a NAMED, PRINTED reason. The engine is never stubbed: a stubbed engine
# would defeat the only thing the `:wasm` tests exist to establish. CI always vendors the
# wasm, so `:wasm` always runs there.
#
# `:slow` tests are excluded by default; run them with `mix test --include slow`.

excluded = [:slow]

wasm_path = AshGraphLaw.WasmConfig.wasm_path([])

wasm_verdict =
  case File.read(wasm_path) do
    {:error, reason} ->
      {:unavailable, "#{wasm_path} is not readable (#{inspect(reason)}); run `mix ash_graphlaw.vendor`"}

    {:ok, bytes} ->
      case AshGraphLaw.EngineLoad.admit(bytes, []) do
        {:ok, _admitted} ->
          :ok

        {:error, refusal} ->
          {:unavailable, "#{wasm_path} refused by the engine gate (#{refusal.code}): #{refusal.message}"}
      end
  end

excluded =
  case wasm_verdict do
    :ok ->
      excluded

    {:unavailable, reason} ->
      IO.puts(:stderr, "[wasm] EXCLUDING :wasm -- " <> reason)
      [:wasm | excluded]
  end

ExUnit.start(exclude: excluded)
