# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability do
  @moduledoc ~S"""
  Behaviour implemented by every typed GraphLaw capability module.

  The surface is generated from the GraphLaw capability registry
  (`graphlaw.capability-registry/1`, GraphLaw `26.9.29`, ABI `1`,
  `14` capabilities, registry digest `sha256:8f3ef15bad35fc095e4a832b4cca945414e90152c485dc5a5a92d2ff0f804e16`). Each
  capability module `AshGraphLaw.Capability.<Op>` builds the request map for one
  wire operation, decodes the engine response into a result struct and runs the
  pair on the real engine. Building requests never needs the engine; running
  them does.

  This library exposes GraphLaw. It does not implement RDF, SPARQL, SHACL, ShEx,
  N3, Datalog, entailment or planning semantics, and a decoded result is an
  observation, not authority.
  """

  alias AshGraphLaw.Refusal

  @typedoc "Request arguments: a keyword list or a map with atom or string snake_case keys."
  @type args :: keyword() | map()

  @typedoc "Outcome of a capability: the decoded result or a typed refusal."
  @type outcome :: {:ok, term()} | {:error, Refusal.t()}

  @doc "The wire name of the operation, for example `\"sparql\"`."
  @callback op() :: String.t()

  @doc """
  Coerces `args` against the registry request fields and returns the engine request map,
  including the `"op"` key, or a typed `:invalid_capability_request` refusal.
  """
  @callback build_request(args()) :: {:ok, map()} | {:error, Refusal.t()}

  @doc """
  Decodes an engine response into the capability's result struct. Never raises on unexpected
  shapes; a response that is not a map refuses with `:capability_response_undecodable`.
  """
  @callback decode(term()) :: {:ok, term()} | {:error, Refusal.t()}

  @doc """
  Builds the request, calls the engine with the same options as `AshGraphLaw.call/2` and
  decodes the response.
  """
  @callback run(args(), keyword()) :: outcome()
end
