# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (queries/refusal_codes.rq). DO NOT EDIT.
defmodule AshGraphLaw.Refusal do
  @moduledoc ~S"""
  Typed refusal carried by every `{:error, _}` this library returns.

  A refusal is an observation about one exact input: it names a closed `t:code/0`,
  a closed `t:class/0`, and the Chatman failure-taxonomy `broken_term` the refusal
  witnesses. GraphLaw derives and validates; it never authorizes, so a refusal
  never grants or withdraws authority.

  `:raw` keeps the whole engine error map exactly as decoded (lossless, so fields this
  library does not know are never dropped); it is `nil` for client-side refusals built
  with `new/3`, `build/3` or a per-code constructor.

  The code table (`codes/0`, `class_of/1`, `broken_term_of/1`, `doc_of/1`) and the
  per-code constructors are generated from the ontology rows. Only the mapping of engine
  error payloads onto codes in `from_engine/2` is hand policy
  (UNSUPPORTED(generator-capability)): the engine's error enums are `non_exhaustive`, so
  unknown variants map to `:engine_unclassified` instead of crashing.

  ## Usage

  Build a refusal from the closed table, or with the per-code constructor:

      iex> refusal = AshGraphLaw.Refusal.new(:not_admitted)
      iex> {refusal.code, refusal.class}
      {:not_admitted, :refused_admission}

      iex> AshGraphLaw.Refusal.not_admitted().code
      :not_admitted

  A refusal is an `Exception`, so it can be raised or matched:

      iex> {:error, %AshGraphLaw.Refusal{code: code}} = {:error, AshGraphLaw.Refusal.not_admitted()}
      iex> code
      :not_admitted

  ## Typed failure table

  Every code, its class, its source and the failure-taxonomy term it witnesses. The
  table is closed: no code exists outside it and none is added without an ontology row.

    * `:not_admitted` - class `:refused_admission`, source `engine`,
      witnesses `:mu_on_O`. The engine evaluated the admission steps and refused the input: at least one step (SHACL, N3, RDFS, OWL-RL, hooks) did not admit it.
    * `:plan_refused` - class `:refused_admission`, source `engine`,
      witnesses `:mu_on_O`. The engine's plan step refused: the submitted plan violates a precondition or goal it can verify against the data.
    * `:receipt_required` - class `:refused_admission`, source `engine`,
      witnesses `:mu_on_O`. A require_receipt step found no receipt for the required step, so the transition has no receipted admission behind it.
    * `:lease_refused` - class `:refused_authority`, source `engine`,
      witnesses `:R_missing_authority`. The engine refused the supplied lease: it is unsigned, expired, outside the allowed clock skew, or signed by an untrusted key.
    * `:resource_limit` - class `:blocked_resource`, source `engine`,
      witnesses `:R_missing_consequence`. The engine hit a resource limit (input size, fuel, or memory) before it could decide; nothing was admitted or refused.
    * `:policy_refused` - class `:refused_admission`, source `engine`,
      witnesses `:mu_on_O`. The engine refused the request under its policy: the requested authority ceiling or operation is not permitted.
    * `:engine_refused` - class `:refused_structure`, source `engine`,
      witnesses `:mu_on_O`. The engine refused the request for a structural reason (malformed op, data, or steps) reported under its error kind.
    * `:engine_unclassified` - class `:unsupported`, source `engine`,
      witnesses `:R_missing_standing`. The engine returned a refusal variant this library does not know; it is carried verbatim and classified unsupported rather than guessed.
    * `:wasm_not_vendored` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. No GraphLaw WASM binary exists at the resolved path; run mix ash_graphlaw.vendor to fetch the pinned release asset.
    * `:wasm_unreadable` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The GraphLaw WASM file exists at the resolved path but could not be read.
    * `:wasm_invalid` - class `:refused_structure`, source `host`,
      witnesses `:R_missing_identity`. The bytes at the WASM path do not compile as a WebAssembly module.
    * `:wasm_digest_mismatch` - class `:refused_identity`, source `host`,
      witnesses `:R_missing_identity`. The sha256 of the WASM bytes differs from the pinned digest, so the module is not the admitted GraphLaw release.
    * `:wasm_import_surface_mismatch` - class `:refused_identity`, source `host`,
      witnesses `:R_missing_identity`. The module imports something other than the wasi_snapshot_preview1 surface, so it is not the pinned GraphLaw shape.
    * `:wasm_missing_export` - class `:refused_structure`, source `host`,
      witnesses `:R_missing_identity`. The module lacks a required export (gl_alloc, gl_call, gl_free, or memory).
    * `:abi_version_mismatch` - class `:refused_identity`, source `host`,
      witnesses `:R_missing_identity`. The engine reports an ABI version different from the version this library was built for.
    * `:instantiation_failed` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The WASM module passed admission but could not be instantiated by the runtime.
    * `:abi_failure` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. A GraphLaw ABI call violated its contract, for example a bad pointer or a failed allocation; the instance is recycled.
    * `:call_trapped` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The WASM call trapped while executing; the instance is recycled.
    * `:call_exited` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The WASM program exited during the call; the instance is recycled.
    * `:call_timeout` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The call did not finish within the configured timeout_ms.
    * `:saturated` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The host queue is full (max_queue), so the request was shed instead of waiting.
    * `:host_not_started` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. No GraphLaw host process is running under the requested server name.
    * `:fuel_exhausted` - class `:blocked_resource`, source `host`,
      witnesses `:R_missing_consequence`. The call used up its fuel budget before the engine returned.
    * `:invalid_encoding` - class `:refused_structure`, source `host`,
      witnesses `:mu_on_O`. The request contained a string that is not valid UTF-8 and was refused before reaching the engine.
    * `:invalid_json` - class `:refused_structure`, source `host`,
      witnesses `:mu_on_O`. A request could not be encoded as JSON, or an engine response was not valid JSON.
    * `:malformed_response` - class `:refused_structure`, source `host`,
      witnesses `:mu_on_O`. The engine response was valid JSON but lacked the expected envelope fields.
    * `:unknown_admission` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. The named admission is not declared in the resource's graphlaw section.
    * `:duplicate_admission` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. Two admissions in one resource share the same name.
    * `:missing_law_module` - class `:refused_structure`, source `ash`,
      witnesses `:admission_vacuous`. An admission uses a step that needs a payload but declares no law module, so it would admit vacuously.
    * `:invalid_runtime_option` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. A graphlaw runtime option is out of range: timeout_ms must be positive and max_skew_secs non-negative.
    * `:invalid_trusted_key` - class `:refused_authority`, source `ash`,
      witnesses `:R_missing_authority`. A trusted key is not a 64-character hexadecimal public key, so lease signatures cannot be checked against it.
    * `:ceiling_unmet` - class `:refused_authority`, source `ash`,
      witnesses `:R_missing_authority`. The lease in the changeset context does not reach the ceiling the admission requires; refused before the engine is called.
    * `:projection_failed` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. The projection module could not produce N-Triples data for the subject.
    * `:law_module_failed` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. The law module raised or returned a value that is not a list of step maps.
    * `:unsupported_step` - class `:unsupported`, source `ash`,
      witnesses `:admission_vacuous`. The admission step is not supported by this library version or by the pinned engine release.
    * `:invalid_capability_request` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. A typed capability request failed client-side validation before the engine was called: unknown top-level keys, missing required fields, or a value whose type does not match the registry field type.
    * `:unknown_capability` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. The named capability is not in the vendored GraphLaw capability registry, so no typed request can be built for it.
    * `:capability_not_declared` - class `:refused_authority`, source `ash`,
      witnesses `:R_missing_authority`. The resource declares at least one capability in its graphlaw section but not this one, so the op is refused before the engine is called.
    * `:capability_parity_drift` - class `:refused_identity`, source `ash`,
      witnesses `:R_missing_identity`. The live engine, the vendored capability registry, the typed module set or the admission DSL disagree about the supported capability set; the parity court refuses.
    * `:capability_response_undecodable` - class `:refused_structure`, source `ash`,
      witnesses `:mu_on_O`. The engine returned a capability response that is not a JSON object, so it cannot be decoded into a typed result; the raw value is preserved on the refusal.

  ## Classes


    * `:refused_admission` - 4 code(s)
    * `:refused_authority` - 4 code(s)
    * `:blocked_resource` - 11 code(s)
    * `:refused_structure` - 15 code(s)
    * `:unsupported` - 2 code(s)
    * `:refused_identity` - 4 code(s)

  ## Failure-taxonomy terms


    * `:mu_on_O` - 16 code(s)
    * `:R_missing_authority` - 4 code(s)
    * `:R_missing_consequence` - 11 code(s)
    * `:R_missing_standing` - 1 code(s)
    * `:R_missing_identity` - 6 code(s)
    * `:admission_vacuous` - 2 code(s)
  """

  @codes [
    :not_admitted,
    :plan_refused,
    :receipt_required,
    :lease_refused,
    :resource_limit,
    :policy_refused,
    :engine_refused,
    :engine_unclassified,
    :wasm_not_vendored,
    :wasm_unreadable,
    :wasm_invalid,
    :wasm_digest_mismatch,
    :wasm_import_surface_mismatch,
    :wasm_missing_export,
    :abi_version_mismatch,
    :instantiation_failed,
    :abi_failure,
    :call_trapped,
    :call_exited,
    :call_timeout,
    :saturated,
    :host_not_started,
    :fuel_exhausted,
    :invalid_encoding,
    :invalid_json,
    :malformed_response,
    :unknown_admission,
    :duplicate_admission,
    :missing_law_module,
    :invalid_runtime_option,
    :invalid_trusted_key,
    :ceiling_unmet,
    :projection_failed,
    :law_module_failed,
    :unsupported_step,
    :invalid_capability_request,
    :unknown_capability,
    :capability_not_declared,
    :capability_parity_drift,
    :capability_response_undecodable
  ]

  @classes [
    :refused_admission,
    :refused_authority,
    :blocked_resource,
    :refused_structure,
    :unsupported,
    :refused_identity
  ]

  @broken_terms [
    :mu_on_O,
    :R_missing_authority,
    :R_missing_consequence,
    :R_missing_standing,
    :R_missing_identity,
    :admission_vacuous
  ]

  # UNSUPPORTED(generator-capability): engine error payload -> code policy.
  @engine_codes %{
    "NotAdmitted" => :not_admitted,
    "PlanRefused" => :plan_refused,
    "ReceiptRequired" => :receipt_required,
    "LeaseRefused" => :lease_refused,
    "ResourceLimit" => :resource_limit,
    "PolicyRefused" => :policy_refused,
    # Real engine codes (graphlaw src/abi.rs) that are refusals of the same two families.
    "ReceiptRefused" => :receipt_required,
    "UnverifiedLeaseRefused" => :lease_refused,
    # Generic engine refusal; the engine kind is carried separately in `details.kind`.
    "Refused" => :engine_refused
  }

  # Engine `RefusalKind` variants (graphlaw src/dialect.rs). The engine reports a generic refusal
  # as `details.code "Refused"` plus its kind, so a known kind without a table code is
  # `:engine_refused`; an unknown kind is a future variant and stays `:engine_unclassified`.
  @engine_kinds ~w(NotSemanticContent Ambiguous EngineRejected Unsupported ResourceLimit)

  for {engine_name, code} <- @engine_codes, code not in @codes do
    raise CompileError,
      description: "engine code #{engine_name} maps to #{inspect(code)}, which is absent from the generated code table"
  end

  @typedoc "Closed union of every refusal code."
  @type code ::
          :not_admitted
          | :plan_refused
          | :receipt_required
          | :lease_refused
          | :resource_limit
          | :policy_refused
          | :engine_refused
          | :engine_unclassified
          | :wasm_not_vendored
          | :wasm_unreadable
          | :wasm_invalid
          | :wasm_digest_mismatch
          | :wasm_import_surface_mismatch
          | :wasm_missing_export
          | :abi_version_mismatch
          | :instantiation_failed
          | :abi_failure
          | :call_trapped
          | :call_exited
          | :call_timeout
          | :saturated
          | :host_not_started
          | :fuel_exhausted
          | :invalid_encoding
          | :invalid_json
          | :malformed_response
          | :unknown_admission
          | :duplicate_admission
          | :missing_law_module
          | :invalid_runtime_option
          | :invalid_trusted_key
          | :ceiling_unmet
          | :projection_failed
          | :law_module_failed
          | :unsupported_step
          | :invalid_capability_request
          | :unknown_capability
          | :capability_not_declared
          | :capability_parity_drift
          | :capability_response_undecodable

  @typedoc "Closed union of refusal classes."
  @type class ::
          :refused_admission
          | :refused_authority
          | :blocked_resource
          | :refused_structure
          | :unsupported
          | :refused_identity

  @typedoc "Chatman failure-taxonomy term a refusal witnesses."
  @type broken_term ::
          :mu_on_O
          | :R_missing_authority
          | :R_missing_consequence
          | :R_missing_standing
          | :R_missing_identity
          | :admission_vacuous

  @typedoc "A typed refusal: closed `code`, its `class` and `broken_term`, engine provenance and `details`."
  @type t :: %__MODULE__{
          code: code(),
          class: class(),
          kind: String.t() | nil,
          engine: String.t() | nil,
          dialect: String.t() | nil,
          message: String.t(),
          details: map(),
          broken_term: broken_term(),
          raw: map() | nil
        }

  defexception code: nil,
               class: nil,
               kind: nil,
               engine: nil,
               dialect: nil,
               message: nil,
               details: %{},
               broken_term: nil,
               raw: nil

  @doc """
  Every refusal code, in ontology order.

      iex> :not_admitted in AshGraphLaw.Refusal.codes()
      true
  """
  @spec codes() :: [code()]
  def codes, do: @codes

  @doc """
  Every refusal class.

      iex> :refused_admission in AshGraphLaw.Refusal.classes()
      true
  """
  @spec classes() :: [class()]
  def classes, do: @classes

  @doc "Every failure-taxonomy term a refusal can witness."
  @spec broken_terms() :: [broken_term()]
  def broken_terms, do: @broken_terms

  @doc """
  The class of a code. Raises `ArgumentError` for a code outside the closed table.

      iex> AshGraphLaw.Refusal.class_of(:not_admitted)
      :refused_admission

      iex> AshGraphLaw.Refusal.class_of(:not_a_code)
      ** (ArgumentError) unknown refusal code: :not_a_code
  """
  @spec class_of(code()) :: class()
  def class_of(:not_admitted), do: :refused_admission
  def class_of(:plan_refused), do: :refused_admission
  def class_of(:receipt_required), do: :refused_admission
  def class_of(:lease_refused), do: :refused_authority
  def class_of(:resource_limit), do: :blocked_resource
  def class_of(:policy_refused), do: :refused_admission
  def class_of(:engine_refused), do: :refused_structure
  def class_of(:engine_unclassified), do: :unsupported
  def class_of(:wasm_not_vendored), do: :blocked_resource
  def class_of(:wasm_unreadable), do: :blocked_resource
  def class_of(:wasm_invalid), do: :refused_structure
  def class_of(:wasm_digest_mismatch), do: :refused_identity
  def class_of(:wasm_import_surface_mismatch), do: :refused_identity
  def class_of(:wasm_missing_export), do: :refused_structure
  def class_of(:abi_version_mismatch), do: :refused_identity
  def class_of(:instantiation_failed), do: :blocked_resource
  def class_of(:abi_failure), do: :blocked_resource
  def class_of(:call_trapped), do: :blocked_resource
  def class_of(:call_exited), do: :blocked_resource
  def class_of(:call_timeout), do: :blocked_resource
  def class_of(:saturated), do: :blocked_resource
  def class_of(:host_not_started), do: :blocked_resource
  def class_of(:fuel_exhausted), do: :blocked_resource
  def class_of(:invalid_encoding), do: :refused_structure
  def class_of(:invalid_json), do: :refused_structure
  def class_of(:malformed_response), do: :refused_structure
  def class_of(:unknown_admission), do: :refused_structure
  def class_of(:duplicate_admission), do: :refused_structure
  def class_of(:missing_law_module), do: :refused_structure
  def class_of(:invalid_runtime_option), do: :refused_structure
  def class_of(:invalid_trusted_key), do: :refused_authority
  def class_of(:ceiling_unmet), do: :refused_authority
  def class_of(:projection_failed), do: :refused_structure
  def class_of(:law_module_failed), do: :refused_structure
  def class_of(:unsupported_step), do: :unsupported
  def class_of(:invalid_capability_request), do: :refused_structure
  def class_of(:unknown_capability), do: :refused_structure
  def class_of(:capability_not_declared), do: :refused_authority
  def class_of(:capability_parity_drift), do: :refused_identity
  def class_of(:capability_response_undecodable), do: :refused_structure
  def class_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc """
  The failure-taxonomy term of a code. Raises `ArgumentError` for a code outside the closed table.

      iex> AshGraphLaw.Refusal.broken_term_of(:not_admitted)
      :mu_on_O
  """
  @spec broken_term_of(code()) :: broken_term()
  def broken_term_of(:not_admitted), do: :mu_on_O
  def broken_term_of(:plan_refused), do: :mu_on_O
  def broken_term_of(:receipt_required), do: :mu_on_O
  def broken_term_of(:lease_refused), do: :R_missing_authority
  def broken_term_of(:resource_limit), do: :R_missing_consequence
  def broken_term_of(:policy_refused), do: :mu_on_O
  def broken_term_of(:engine_refused), do: :mu_on_O
  def broken_term_of(:engine_unclassified), do: :R_missing_standing
  def broken_term_of(:wasm_not_vendored), do: :R_missing_consequence
  def broken_term_of(:wasm_unreadable), do: :R_missing_consequence
  def broken_term_of(:wasm_invalid), do: :R_missing_identity
  def broken_term_of(:wasm_digest_mismatch), do: :R_missing_identity
  def broken_term_of(:wasm_import_surface_mismatch), do: :R_missing_identity
  def broken_term_of(:wasm_missing_export), do: :R_missing_identity
  def broken_term_of(:abi_version_mismatch), do: :R_missing_identity
  def broken_term_of(:instantiation_failed), do: :R_missing_consequence
  def broken_term_of(:abi_failure), do: :R_missing_consequence
  def broken_term_of(:call_trapped), do: :R_missing_consequence
  def broken_term_of(:call_exited), do: :R_missing_consequence
  def broken_term_of(:call_timeout), do: :R_missing_consequence
  def broken_term_of(:saturated), do: :R_missing_consequence
  def broken_term_of(:host_not_started), do: :R_missing_consequence
  def broken_term_of(:fuel_exhausted), do: :R_missing_consequence
  def broken_term_of(:invalid_encoding), do: :mu_on_O
  def broken_term_of(:invalid_json), do: :mu_on_O
  def broken_term_of(:malformed_response), do: :mu_on_O
  def broken_term_of(:unknown_admission), do: :mu_on_O
  def broken_term_of(:duplicate_admission), do: :mu_on_O
  def broken_term_of(:missing_law_module), do: :admission_vacuous
  def broken_term_of(:invalid_runtime_option), do: :mu_on_O
  def broken_term_of(:invalid_trusted_key), do: :R_missing_authority
  def broken_term_of(:ceiling_unmet), do: :R_missing_authority
  def broken_term_of(:projection_failed), do: :mu_on_O
  def broken_term_of(:law_module_failed), do: :mu_on_O
  def broken_term_of(:unsupported_step), do: :admission_vacuous
  def broken_term_of(:invalid_capability_request), do: :mu_on_O
  def broken_term_of(:unknown_capability), do: :mu_on_O
  def broken_term_of(:capability_not_declared), do: :R_missing_authority
  def broken_term_of(:capability_parity_drift), do: :R_missing_identity
  def broken_term_of(:capability_response_undecodable), do: :mu_on_O
  def broken_term_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc """
  The one-line meaning of a code. Raises `ArgumentError` for a code outside the closed table.

      iex> is_binary(AshGraphLaw.Refusal.doc_of(:not_admitted))
      true
  """
  @spec doc_of(code()) :: String.t()
  def doc_of(:not_admitted),
    do:
      "The engine evaluated the admission steps and refused the input: at least one step (SHACL, N3, RDFS, OWL-RL, hooks) did not admit it."

  def doc_of(:plan_refused),
    do:
      "The engine\'s plan step refused: the submitted plan violates a precondition or goal it can verify against the data."

  def doc_of(:receipt_required),
    do:
      "A require_receipt step found no receipt for the required step, so the transition has no receipted admission behind it."

  def doc_of(:lease_refused),
    do:
      "The engine refused the supplied lease: it is unsigned, expired, outside the allowed clock skew, or signed by an untrusted key."

  def doc_of(:resource_limit),
    do:
      "The engine hit a resource limit (input size, fuel, or memory) before it could decide; nothing was admitted or refused."

  def doc_of(:policy_refused),
    do:
      "The engine refused the request under its policy: the requested authority ceiling or operation is not permitted."

  def doc_of(:engine_refused),
    do:
      "The engine refused the request for a structural reason (malformed op, data, or steps) reported under its error kind."

  def doc_of(:engine_unclassified),
    do:
      "The engine returned a refusal variant this library does not know; it is carried verbatim and classified unsupported rather than guessed."

  def doc_of(:wasm_not_vendored),
    do:
      "No GraphLaw WASM binary exists at the resolved path; run mix ash_graphlaw.vendor to fetch the pinned release asset."

  def doc_of(:wasm_unreadable), do: "The GraphLaw WASM file exists at the resolved path but could not be read."
  def doc_of(:wasm_invalid), do: "The bytes at the WASM path do not compile as a WebAssembly module."

  def doc_of(:wasm_digest_mismatch),
    do:
      "The sha256 of the WASM bytes differs from the pinned digest, so the module is not the admitted GraphLaw release."

  def doc_of(:wasm_import_surface_mismatch),
    do:
      "The module imports something other than the wasi_snapshot_preview1 surface, so it is not the pinned GraphLaw shape."

  def doc_of(:wasm_missing_export), do: "The module lacks a required export (gl_alloc, gl_call, gl_free, or memory)."

  def doc_of(:abi_version_mismatch),
    do: "The engine reports an ABI version different from the version this library was built for."

  def doc_of(:instantiation_failed),
    do: "The WASM module passed admission but could not be instantiated by the runtime."

  def doc_of(:abi_failure),
    do:
      "A GraphLaw ABI call violated its contract, for example a bad pointer or a failed allocation; the instance is recycled."

  def doc_of(:call_trapped), do: "The WASM call trapped while executing; the instance is recycled."
  def doc_of(:call_exited), do: "The WASM program exited during the call; the instance is recycled."
  def doc_of(:call_timeout), do: "The call did not finish within the configured timeout_ms."
  def doc_of(:saturated), do: "The host queue is full (max_queue), so the request was shed instead of waiting."
  def doc_of(:host_not_started), do: "No GraphLaw host process is running under the requested server name."
  def doc_of(:fuel_exhausted), do: "The call used up its fuel budget before the engine returned."

  def doc_of(:invalid_encoding),
    do: "The request contained a string that is not valid UTF-8 and was refused before reaching the engine."

  def doc_of(:invalid_json), do: "A request could not be encoded as JSON, or an engine response was not valid JSON."
  def doc_of(:malformed_response), do: "The engine response was valid JSON but lacked the expected envelope fields."
  def doc_of(:unknown_admission), do: "The named admission is not declared in the resource\'s graphlaw section."
  def doc_of(:duplicate_admission), do: "Two admissions in one resource share the same name."

  def doc_of(:missing_law_module),
    do: "An admission uses a step that needs a payload but declares no law module, so it would admit vacuously."

  def doc_of(:invalid_runtime_option),
    do: "A graphlaw runtime option is out of range: timeout_ms must be positive and max_skew_secs non-negative."

  def doc_of(:invalid_trusted_key),
    do: "A trusted key is not a 64-character hexadecimal public key, so lease signatures cannot be checked against it."

  def doc_of(:ceiling_unmet),
    do:
      "The lease in the changeset context does not reach the ceiling the admission requires; refused before the engine is called."

  def doc_of(:projection_failed), do: "The projection module could not produce N-Triples data for the subject."
  def doc_of(:law_module_failed), do: "The law module raised or returned a value that is not a list of step maps."

  def doc_of(:unsupported_step),
    do: "The admission step is not supported by this library version or by the pinned engine release."

  def doc_of(:invalid_capability_request),
    do:
      "A typed capability request failed client-side validation before the engine was called: unknown top-level keys, missing required fields, or a value whose type does not match the registry field type."

  def doc_of(:unknown_capability),
    do:
      "The named capability is not in the vendored GraphLaw capability registry, so no typed request can be built for it."

  def doc_of(:capability_not_declared),
    do:
      "The resource declares at least one capability in its graphlaw section but not this one, so the op is refused before the engine is called."

  def doc_of(:capability_parity_drift),
    do:
      "The live engine, the vendored capability registry, the typed module set or the admission DSL disagree about the supported capability set; the parity court refuses."

  def doc_of(:capability_response_undecodable),
    do:
      "The engine returned a capability response that is not a JSON object, so it cannot be decoded into a typed result; the raw value is preserved on the refusal."

  def doc_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc """
  Builds a refusal for `code`, filling `class` and `broken_term` from the closed table.

  A nil or empty `message` defaults to the code's meaning (`doc_of/1`). Raises
  `ArgumentError` for a code outside the closed table.

      iex> refusal = AshGraphLaw.Refusal.new(:not_admitted, "custom", %{"k" => 1})
      iex> {refusal.message, refusal.details}
      {"custom", %{"k" => 1}}

      iex> AshGraphLaw.Refusal.new(:not_admitted).message == AshGraphLaw.Refusal.doc_of(:not_admitted)
      true
  """
  @spec new(code(), String.t() | nil, map()) :: t()
  def new(code, message \\ nil, details \\ %{}) when is_map(details) do
    %__MODULE__{
      code: code,
      class: class_of(code),
      broken_term: broken_term_of(code),
      message: if(is_binary(message) and message != "", do: message, else: doc_of(code)),
      details: details
    }
  end

  @doc """
  Builds a client-side refusal for `code` with an explicit `message`, validating `code`
  against the closed table.

  Unlike `new/3` the message is required. `class` and `broken_term` come from the table and
  `:raw` is `nil`. Raises `ArgumentError` for a code outside the closed table.

      iex> refusal = AshGraphLaw.Refusal.build(:not_admitted, "custom", %{"k" => 1})
      iex> {refusal.code, refusal.message, refusal.details, refusal.raw}
      {:not_admitted, "custom", %{"k" => 1}, nil}

      iex> AshGraphLaw.Refusal.build(:not_a_code, "x")
      ** (ArgumentError) unknown refusal code: :not_a_code
  """
  @spec build(code(), String.t(), map()) :: t()
  def build(code, message, details \\ %{}) when is_binary(message) and is_map(details), do: new(code, message, details)

  # Per-code constructors, one per ontology row. Each shares the doc pattern below and
  # delegates to `new/3`, so class and broken_term always come from the closed table.

  @doc """
  Builds a `:not_admitted` refusal (class `:refused_admission`, source `engine`,
  witnesses `:mu_on_O`).

  The engine evaluated the admission steps and refused the input: at least one step (SHACL, N3, RDFS, OWL-RL, hooks) did not admit it.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec not_admitted(String.t() | nil, map()) :: t()
  def not_admitted(message \\ nil, details \\ %{}) when is_map(details), do: new(:not_admitted, message, details)

  @doc """
  Builds a `:plan_refused` refusal (class `:refused_admission`, source `engine`,
  witnesses `:mu_on_O`).

  The engine's plan step refused: the submitted plan violates a precondition or goal it can verify against the data.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec plan_refused(String.t() | nil, map()) :: t()
  def plan_refused(message \\ nil, details \\ %{}) when is_map(details), do: new(:plan_refused, message, details)

  @doc """
  Builds a `:receipt_required` refusal (class `:refused_admission`, source `engine`,
  witnesses `:mu_on_O`).

  A require_receipt step found no receipt for the required step, so the transition has no receipted admission behind it.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec receipt_required(String.t() | nil, map()) :: t()
  def receipt_required(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:receipt_required, message, details)

  @doc """
  Builds a `:lease_refused` refusal (class `:refused_authority`, source `engine`,
  witnesses `:R_missing_authority`).

  The engine refused the supplied lease: it is unsigned, expired, outside the allowed clock skew, or signed by an untrusted key.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec lease_refused(String.t() | nil, map()) :: t()
  def lease_refused(message \\ nil, details \\ %{}) when is_map(details), do: new(:lease_refused, message, details)

  @doc """
  Builds a `:resource_limit` refusal (class `:blocked_resource`, source `engine`,
  witnesses `:R_missing_consequence`).

  The engine hit a resource limit (input size, fuel, or memory) before it could decide; nothing was admitted or refused.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec resource_limit(String.t() | nil, map()) :: t()
  def resource_limit(message \\ nil, details \\ %{}) when is_map(details), do: new(:resource_limit, message, details)

  @doc """
  Builds a `:policy_refused` refusal (class `:refused_admission`, source `engine`,
  witnesses `:mu_on_O`).

  The engine refused the request under its policy: the requested authority ceiling or operation is not permitted.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec policy_refused(String.t() | nil, map()) :: t()
  def policy_refused(message \\ nil, details \\ %{}) when is_map(details), do: new(:policy_refused, message, details)

  @doc """
  Builds a `:engine_refused` refusal (class `:refused_structure`, source `engine`,
  witnesses `:mu_on_O`).

  The engine refused the request for a structural reason (malformed op, data, or steps) reported under its error kind.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec engine_refused(String.t() | nil, map()) :: t()
  def engine_refused(message \\ nil, details \\ %{}) when is_map(details), do: new(:engine_refused, message, details)

  @doc """
  Builds a `:engine_unclassified` refusal (class `:unsupported`, source `engine`,
  witnesses `:R_missing_standing`).

  The engine returned a refusal variant this library does not know; it is carried verbatim and classified unsupported rather than guessed.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec engine_unclassified(String.t() | nil, map()) :: t()
  def engine_unclassified(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:engine_unclassified, message, details)

  @doc """
  Builds a `:wasm_not_vendored` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  No GraphLaw WASM binary exists at the resolved path; run mix ash_graphlaw.vendor to fetch the pinned release asset.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_not_vendored(String.t() | nil, map()) :: t()
  def wasm_not_vendored(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:wasm_not_vendored, message, details)

  @doc """
  Builds a `:wasm_unreadable` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The GraphLaw WASM file exists at the resolved path but could not be read.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_unreadable(String.t() | nil, map()) :: t()
  def wasm_unreadable(message \\ nil, details \\ %{}) when is_map(details), do: new(:wasm_unreadable, message, details)

  @doc """
  Builds a `:wasm_invalid` refusal (class `:refused_structure`, source `host`,
  witnesses `:R_missing_identity`).

  The bytes at the WASM path do not compile as a WebAssembly module.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_invalid(String.t() | nil, map()) :: t()
  def wasm_invalid(message \\ nil, details \\ %{}) when is_map(details), do: new(:wasm_invalid, message, details)

  @doc """
  Builds a `:wasm_digest_mismatch` refusal (class `:refused_identity`, source `host`,
  witnesses `:R_missing_identity`).

  The sha256 of the WASM bytes differs from the pinned digest, so the module is not the admitted GraphLaw release.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_digest_mismatch(String.t() | nil, map()) :: t()
  def wasm_digest_mismatch(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:wasm_digest_mismatch, message, details)

  @doc """
  Builds a `:wasm_import_surface_mismatch` refusal (class `:refused_identity`, source `host`,
  witnesses `:R_missing_identity`).

  The module imports something other than the wasi_snapshot_preview1 surface, so it is not the pinned GraphLaw shape.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_import_surface_mismatch(String.t() | nil, map()) :: t()
  def wasm_import_surface_mismatch(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:wasm_import_surface_mismatch, message, details)

  @doc """
  Builds a `:wasm_missing_export` refusal (class `:refused_structure`, source `host`,
  witnesses `:R_missing_identity`).

  The module lacks a required export (gl_alloc, gl_call, gl_free, or memory).

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec wasm_missing_export(String.t() | nil, map()) :: t()
  def wasm_missing_export(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:wasm_missing_export, message, details)

  @doc """
  Builds a `:abi_version_mismatch` refusal (class `:refused_identity`, source `host`,
  witnesses `:R_missing_identity`).

  The engine reports an ABI version different from the version this library was built for.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec abi_version_mismatch(String.t() | nil, map()) :: t()
  def abi_version_mismatch(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:abi_version_mismatch, message, details)

  @doc """
  Builds a `:instantiation_failed` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The WASM module passed admission but could not be instantiated by the runtime.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec instantiation_failed(String.t() | nil, map()) :: t()
  def instantiation_failed(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:instantiation_failed, message, details)

  @doc """
  Builds a `:abi_failure` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  A GraphLaw ABI call violated its contract, for example a bad pointer or a failed allocation; the instance is recycled.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec abi_failure(String.t() | nil, map()) :: t()
  def abi_failure(message \\ nil, details \\ %{}) when is_map(details), do: new(:abi_failure, message, details)

  @doc """
  Builds a `:call_trapped` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The WASM call trapped while executing; the instance is recycled.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec call_trapped(String.t() | nil, map()) :: t()
  def call_trapped(message \\ nil, details \\ %{}) when is_map(details), do: new(:call_trapped, message, details)

  @doc """
  Builds a `:call_exited` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The WASM program exited during the call; the instance is recycled.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec call_exited(String.t() | nil, map()) :: t()
  def call_exited(message \\ nil, details \\ %{}) when is_map(details), do: new(:call_exited, message, details)

  @doc """
  Builds a `:call_timeout` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The call did not finish within the configured timeout_ms.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec call_timeout(String.t() | nil, map()) :: t()
  def call_timeout(message \\ nil, details \\ %{}) when is_map(details), do: new(:call_timeout, message, details)

  @doc """
  Builds a `:saturated` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The host queue is full (max_queue), so the request was shed instead of waiting.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec saturated(String.t() | nil, map()) :: t()
  def saturated(message \\ nil, details \\ %{}) when is_map(details), do: new(:saturated, message, details)

  @doc """
  Builds a `:host_not_started` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  No GraphLaw host process is running under the requested server name.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec host_not_started(String.t() | nil, map()) :: t()
  def host_not_started(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:host_not_started, message, details)

  @doc """
  Builds a `:fuel_exhausted` refusal (class `:blocked_resource`, source `host`,
  witnesses `:R_missing_consequence`).

  The call used up its fuel budget before the engine returned.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec fuel_exhausted(String.t() | nil, map()) :: t()
  def fuel_exhausted(message \\ nil, details \\ %{}) when is_map(details), do: new(:fuel_exhausted, message, details)

  @doc """
  Builds a `:invalid_encoding` refusal (class `:refused_structure`, source `host`,
  witnesses `:mu_on_O`).

  The request contained a string that is not valid UTF-8 and was refused before reaching the engine.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec invalid_encoding(String.t() | nil, map()) :: t()
  def invalid_encoding(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:invalid_encoding, message, details)

  @doc """
  Builds a `:invalid_json` refusal (class `:refused_structure`, source `host`,
  witnesses `:mu_on_O`).

  A request could not be encoded as JSON, or an engine response was not valid JSON.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec invalid_json(String.t() | nil, map()) :: t()
  def invalid_json(message \\ nil, details \\ %{}) when is_map(details), do: new(:invalid_json, message, details)

  @doc """
  Builds a `:malformed_response` refusal (class `:refused_structure`, source `host`,
  witnesses `:mu_on_O`).

  The engine response was valid JSON but lacked the expected envelope fields.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec malformed_response(String.t() | nil, map()) :: t()
  def malformed_response(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:malformed_response, message, details)

  @doc """
  Builds a `:unknown_admission` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  The named admission is not declared in the resource's graphlaw section.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec unknown_admission(String.t() | nil, map()) :: t()
  def unknown_admission(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:unknown_admission, message, details)

  @doc """
  Builds a `:duplicate_admission` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  Two admissions in one resource share the same name.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec duplicate_admission(String.t() | nil, map()) :: t()
  def duplicate_admission(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:duplicate_admission, message, details)

  @doc """
  Builds a `:missing_law_module` refusal (class `:refused_structure`, source `ash`,
  witnesses `:admission_vacuous`).

  An admission uses a step that needs a payload but declares no law module, so it would admit vacuously.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec missing_law_module(String.t() | nil, map()) :: t()
  def missing_law_module(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:missing_law_module, message, details)

  @doc """
  Builds a `:invalid_runtime_option` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  A graphlaw runtime option is out of range: timeout_ms must be positive and max_skew_secs non-negative.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec invalid_runtime_option(String.t() | nil, map()) :: t()
  def invalid_runtime_option(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:invalid_runtime_option, message, details)

  @doc """
  Builds a `:invalid_trusted_key` refusal (class `:refused_authority`, source `ash`,
  witnesses `:R_missing_authority`).

  A trusted key is not a 64-character hexadecimal public key, so lease signatures cannot be checked against it.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec invalid_trusted_key(String.t() | nil, map()) :: t()
  def invalid_trusted_key(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:invalid_trusted_key, message, details)

  @doc """
  Builds a `:ceiling_unmet` refusal (class `:refused_authority`, source `ash`,
  witnesses `:R_missing_authority`).

  The lease in the changeset context does not reach the ceiling the admission requires; refused before the engine is called.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec ceiling_unmet(String.t() | nil, map()) :: t()
  def ceiling_unmet(message \\ nil, details \\ %{}) when is_map(details), do: new(:ceiling_unmet, message, details)

  @doc """
  Builds a `:projection_failed` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  The projection module could not produce N-Triples data for the subject.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec projection_failed(String.t() | nil, map()) :: t()
  def projection_failed(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:projection_failed, message, details)

  @doc """
  Builds a `:law_module_failed` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  The law module raised or returned a value that is not a list of step maps.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec law_module_failed(String.t() | nil, map()) :: t()
  def law_module_failed(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:law_module_failed, message, details)

  @doc """
  Builds a `:unsupported_step` refusal (class `:unsupported`, source `ash`,
  witnesses `:admission_vacuous`).

  The admission step is not supported by this library version or by the pinned engine release.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec unsupported_step(String.t() | nil, map()) :: t()
  def unsupported_step(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:unsupported_step, message, details)

  @doc """
  Builds a `:invalid_capability_request` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  A typed capability request failed client-side validation before the engine was called: unknown top-level keys, missing required fields, or a value whose type does not match the registry field type.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec invalid_capability_request(String.t() | nil, map()) :: t()
  def invalid_capability_request(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:invalid_capability_request, message, details)

  @doc """
  Builds a `:unknown_capability` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  The named capability is not in the vendored GraphLaw capability registry, so no typed request can be built for it.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec unknown_capability(String.t() | nil, map()) :: t()
  def unknown_capability(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:unknown_capability, message, details)

  @doc """
  Builds a `:capability_not_declared` refusal (class `:refused_authority`, source `ash`,
  witnesses `:R_missing_authority`).

  The resource declares at least one capability in its graphlaw section but not this one, so the op is refused before the engine is called.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec capability_not_declared(String.t() | nil, map()) :: t()
  def capability_not_declared(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:capability_not_declared, message, details)

  @doc """
  Builds a `:capability_parity_drift` refusal (class `:refused_identity`, source `ash`,
  witnesses `:R_missing_identity`).

  The live engine, the vendored capability registry, the typed module set or the admission DSL disagree about the supported capability set; the parity court refuses.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec capability_parity_drift(String.t() | nil, map()) :: t()
  def capability_parity_drift(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:capability_parity_drift, message, details)

  @doc """
  Builds a `:capability_response_undecodable` refusal (class `:refused_structure`, source `ash`,
  witnesses `:mu_on_O`).

  The engine returned a capability response that is not a JSON object, so it cannot be decoded into a typed result; the raw value is preserved on the refusal.

  A nil or empty `message` defaults to the code's meaning; `details` is carried unchanged.
  """
  @spec capability_response_undecodable(String.t() | nil, map()) :: t()
  def capability_response_undecodable(message \\ nil, details \\ %{}) when is_map(details),
    do: new(:capability_response_undecodable, message, details)

  @doc """
  Maps an engine error map (string keys, as decoded from the engine response) onto a refusal.

  `error_map["details"]["code"]` selects a specific code (`NotAdmitted`, `PlanRefused`,
  `ReceiptRequired`, `LeaseRefused`, `ResourceLimit`, `PolicyRefused`). Without one, an
  engine `kind` maps to `:engine_refused` with the original kind kept in `:kind`. A detail
  code this library does not know, or a payload with no usable kind, maps to
  `:engine_unclassified`. The whole engine error map is kept in `:raw`; unknown keys are
  merged into `details`. Never raises.

      iex> AshGraphLaw.Refusal.from_engine(%{"details" => %{"code" => "NotAdmitted"}}).code
      :not_admitted

      iex> AshGraphLaw.Refusal.from_engine(%{"kind" => "Ambiguous"}).code
      :engine_refused

      iex> AshGraphLaw.Refusal.from_engine(%{"kind" => "Ambiguous", "x" => 1}).raw
      %{"kind" => "Ambiguous", "x" => 1}

      iex> AshGraphLaw.Refusal.from_engine(:garbage).code
      :engine_unclassified
  """
  @spec from_engine(term(), map()) :: t()
  def from_engine(error_map, details_map \\ %{})

  def from_engine(error_map, details_map) when is_map(error_map) and is_map(details_map) do
    error_details = with_map(Map.get(error_map, "details"))
    kind = string_or_nil(Map.get(error_map, "kind"))
    engine_code = Map.get(error_details, "code", Map.get(details_map, "code"))
    code = engine_code_to_code(engine_code, kind)

    refusal = new(code, string_or_nil(Map.get(error_map, "message")), Map.merge(error_details, details_map))

    %{
      refusal
      | kind: kind,
        engine: string_or_nil(Map.get(error_map, "engine", Map.get(details_map, "engine"))),
        dialect: string_or_nil(Map.get(error_map, "dialect", Map.get(details_map, "dialect"))),
        raw: error_map
    }
  end

  def from_engine(other, details_map) do
    details = if is_map(details_map), do: details_map, else: %{}
    refusal = new(:engine_unclassified, nil, Map.put(details, "raw", inspect(other, limit: 20, printable_limit: 256)))
    %{refusal | raw: if(is_map(other), do: other)}
  end

  @spec engine_code_to_code(term(), String.t() | nil) :: code()
  defp engine_code_to_code(engine_code, kind) when is_binary(engine_code) do
    case Map.fetch(@engine_codes, engine_code) do
      {:ok, code} -> code
      :error -> kind_to_code(kind)
    end
  end

  defp engine_code_to_code(nil, kind), do: kind_to_code(kind)
  defp engine_code_to_code(_engine_code, _kind), do: :engine_unclassified

  defp kind_to_code(kind) when kind in @engine_kinds, do: :engine_refused
  defp kind_to_code(_kind), do: :engine_unclassified

  defp with_map(value) when is_map(value), do: value
  defp with_map(_value), do: %{}

  defp string_or_nil(value) when is_binary(value), do: value
  defp string_or_nil(_value), do: nil

  @doc "Exception message: the refusal message, else `GraphLaw refused: <code>`."
  @impl true
  @spec message(t() | term()) :: String.t()
  def message(%__MODULE__{message: message}) when is_binary(message), do: message
  def message(%__MODULE__{code: code}) when is_atom(code) and not is_nil(code), do: "GraphLaw refused: #{code}"
  def message(_refusal), do: "GraphLaw refused"
end
