# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (queries/refusal_codes.rq). DO NOT EDIT.
defmodule AshGraphLaw.Refusal do
  @moduledoc """
  Typed refusal carried by every `{:error, _}` this library returns.

  A refusal is an observation about one exact input: it names a closed `t:code/0`,
  a closed `t:class/0`, and the Chatman failure-taxonomy `broken_term` the refusal
  witnesses. GraphLaw derives and validates; it never authorizes, so a refusal
  never grants or withdraws authority.

  The code table (`codes/0`, `class_of/1`, `broken_term_of/1`, `doc_of/1`) is generated
  from the ontology rows. Only the mapping of engine error payloads onto codes in
  `from_engine/2` is hand policy (UNSUPPORTED(generator-capability)): the engine's
  error enums are `non_exhaustive`, so unknown variants map to `:engine_unclassified`
  instead of crashing.
  """

  @codes [
    :not_admitted,
    :plan_refused,
    :receipt_required,
    :lease_refused,
    :resource_limit,
    :policy_refused,
    :engine_refused,
    :engine_unclassified,
    :wasm_not_vendored,
    :wasm_unreadable,
    :wasm_invalid,
    :wasm_digest_mismatch,
    :wasm_import_surface_mismatch,
    :wasm_missing_export,
    :abi_version_mismatch,
    :instantiation_failed,
    :abi_failure,
    :call_trapped,
    :call_exited,
    :call_timeout,
    :saturated,
    :host_not_started,
    :fuel_exhausted,
    :invalid_encoding,
    :invalid_json,
    :malformed_response,
    :unknown_admission,
    :duplicate_admission,
    :missing_law_module,
    :invalid_runtime_option,
    :invalid_trusted_key,
    :ceiling_unmet,
    :projection_failed,
    :law_module_failed,
    :unsupported_step
  ]

  @classes [
    :refused_admission,
    :refused_authority,
    :blocked_resource,
    :refused_structure,
    :unsupported,
    :refused_identity
  ]

  @broken_terms [
    :mu_on_O,
    :R_missing_authority,
    :R_missing_consequence,
    :R_missing_standing,
    :R_missing_identity,
    :admission_vacuous
  ]

  # UNSUPPORTED(generator-capability): engine error payload -> code policy.
  @engine_codes %{
    "NotAdmitted" => :not_admitted,
    "PlanRefused" => :plan_refused,
    "ReceiptRequired" => :receipt_required,
    "LeaseRefused" => :lease_refused,
    "ResourceLimit" => :resource_limit,
    "PolicyRefused" => :policy_refused,
    # Real engine codes (graphlaw src/abi.rs) that are refusals of the same two families.
    "ReceiptRefused" => :receipt_required,
    "UnverifiedLeaseRefused" => :lease_refused
  }

  # Engine `RefusalKind` variants (graphlaw src/dialect.rs). The engine reports a generic refusal
  # as `details.code "Refused"` plus its kind, so a known kind without a table code is
  # `:engine_refused`; an unknown kind is a future variant and stays `:engine_unclassified`.
  @engine_kinds ~w(NotSemanticContent Ambiguous EngineRejected Unsupported ResourceLimit)

  for {engine_name, code} <- @engine_codes, code not in @codes do
    raise CompileError,
      description: "engine code #{engine_name} maps to #{inspect(code)}, which is absent from the generated code table"
  end

  @typedoc "Closed union of every refusal code."
  @type code ::
          :not_admitted
          | :plan_refused
          | :receipt_required
          | :lease_refused
          | :resource_limit
          | :policy_refused
          | :engine_refused
          | :engine_unclassified
          | :wasm_not_vendored
          | :wasm_unreadable
          | :wasm_invalid
          | :wasm_digest_mismatch
          | :wasm_import_surface_mismatch
          | :wasm_missing_export
          | :abi_version_mismatch
          | :instantiation_failed
          | :abi_failure
          | :call_trapped
          | :call_exited
          | :call_timeout
          | :saturated
          | :host_not_started
          | :fuel_exhausted
          | :invalid_encoding
          | :invalid_json
          | :malformed_response
          | :unknown_admission
          | :duplicate_admission
          | :missing_law_module
          | :invalid_runtime_option
          | :invalid_trusted_key
          | :ceiling_unmet
          | :projection_failed
          | :law_module_failed
          | :unsupported_step

  @typedoc "Closed union of refusal classes."
  @type class ::
          :refused_admission
          | :refused_authority
          | :blocked_resource
          | :refused_structure
          | :unsupported
          | :refused_identity

  @typedoc "Chatman failure-taxonomy term a refusal witnesses."
  @type broken_term ::
          :mu_on_O
          | :R_missing_authority
          | :R_missing_consequence
          | :R_missing_standing
          | :R_missing_identity
          | :admission_vacuous

  @type t :: %__MODULE__{
          code: code(),
          class: class(),
          kind: String.t() | nil,
          engine: String.t() | nil,
          dialect: String.t() | nil,
          message: String.t(),
          details: map(),
          broken_term: broken_term()
        }

  defexception code: nil,
               class: nil,
               kind: nil,
               engine: nil,
               dialect: nil,
               message: nil,
               details: %{},
               broken_term: nil

  @doc "Every refusal code, in ontology order."
  @spec codes() :: [code()]
  def codes, do: @codes

  @doc "Every refusal class."
  @spec classes() :: [class()]
  def classes, do: @classes

  @doc "Every failure-taxonomy term a refusal can witness."
  @spec broken_terms() :: [broken_term()]
  def broken_terms, do: @broken_terms

  @doc "The class of a code. Raises `ArgumentError` for a code outside the closed table."
  @spec class_of(code()) :: class()
  def class_of(:not_admitted), do: :refused_admission
  def class_of(:plan_refused), do: :refused_admission
  def class_of(:receipt_required), do: :refused_admission
  def class_of(:lease_refused), do: :refused_authority
  def class_of(:resource_limit), do: :blocked_resource
  def class_of(:policy_refused), do: :refused_admission
  def class_of(:engine_refused), do: :refused_structure
  def class_of(:engine_unclassified), do: :unsupported
  def class_of(:wasm_not_vendored), do: :blocked_resource
  def class_of(:wasm_unreadable), do: :blocked_resource
  def class_of(:wasm_invalid), do: :refused_structure
  def class_of(:wasm_digest_mismatch), do: :refused_identity
  def class_of(:wasm_import_surface_mismatch), do: :refused_identity
  def class_of(:wasm_missing_export), do: :refused_structure
  def class_of(:abi_version_mismatch), do: :refused_identity
  def class_of(:instantiation_failed), do: :blocked_resource
  def class_of(:abi_failure), do: :blocked_resource
  def class_of(:call_trapped), do: :blocked_resource
  def class_of(:call_exited), do: :blocked_resource
  def class_of(:call_timeout), do: :blocked_resource
  def class_of(:saturated), do: :blocked_resource
  def class_of(:host_not_started), do: :blocked_resource
  def class_of(:fuel_exhausted), do: :blocked_resource
  def class_of(:invalid_encoding), do: :refused_structure
  def class_of(:invalid_json), do: :refused_structure
  def class_of(:malformed_response), do: :refused_structure
  def class_of(:unknown_admission), do: :refused_structure
  def class_of(:duplicate_admission), do: :refused_structure
  def class_of(:missing_law_module), do: :refused_structure
  def class_of(:invalid_runtime_option), do: :refused_structure
  def class_of(:invalid_trusted_key), do: :refused_authority
  def class_of(:ceiling_unmet), do: :refused_authority
  def class_of(:projection_failed), do: :refused_structure
  def class_of(:law_module_failed), do: :refused_structure
  def class_of(:unsupported_step), do: :unsupported
  def class_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc "The failure-taxonomy term of a code. Raises `ArgumentError` for a code outside the closed table."
  @spec broken_term_of(code()) :: broken_term()
  def broken_term_of(:not_admitted), do: :mu_on_O
  def broken_term_of(:plan_refused), do: :mu_on_O
  def broken_term_of(:receipt_required), do: :mu_on_O
  def broken_term_of(:lease_refused), do: :R_missing_authority
  def broken_term_of(:resource_limit), do: :R_missing_consequence
  def broken_term_of(:policy_refused), do: :mu_on_O
  def broken_term_of(:engine_refused), do: :mu_on_O
  def broken_term_of(:engine_unclassified), do: :R_missing_standing
  def broken_term_of(:wasm_not_vendored), do: :R_missing_consequence
  def broken_term_of(:wasm_unreadable), do: :R_missing_consequence
  def broken_term_of(:wasm_invalid), do: :R_missing_identity
  def broken_term_of(:wasm_digest_mismatch), do: :R_missing_identity
  def broken_term_of(:wasm_import_surface_mismatch), do: :R_missing_identity
  def broken_term_of(:wasm_missing_export), do: :R_missing_identity
  def broken_term_of(:abi_version_mismatch), do: :R_missing_identity
  def broken_term_of(:instantiation_failed), do: :R_missing_consequence
  def broken_term_of(:abi_failure), do: :R_missing_consequence
  def broken_term_of(:call_trapped), do: :R_missing_consequence
  def broken_term_of(:call_exited), do: :R_missing_consequence
  def broken_term_of(:call_timeout), do: :R_missing_consequence
  def broken_term_of(:saturated), do: :R_missing_consequence
  def broken_term_of(:host_not_started), do: :R_missing_consequence
  def broken_term_of(:fuel_exhausted), do: :R_missing_consequence
  def broken_term_of(:invalid_encoding), do: :mu_on_O
  def broken_term_of(:invalid_json), do: :mu_on_O
  def broken_term_of(:malformed_response), do: :mu_on_O
  def broken_term_of(:unknown_admission), do: :mu_on_O
  def broken_term_of(:duplicate_admission), do: :mu_on_O
  def broken_term_of(:missing_law_module), do: :admission_vacuous
  def broken_term_of(:invalid_runtime_option), do: :mu_on_O
  def broken_term_of(:invalid_trusted_key), do: :R_missing_authority
  def broken_term_of(:ceiling_unmet), do: :R_missing_authority
  def broken_term_of(:projection_failed), do: :mu_on_O
  def broken_term_of(:law_module_failed), do: :mu_on_O
  def broken_term_of(:unsupported_step), do: :admission_vacuous
  def broken_term_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc "The one-line meaning of a code. Raises `ArgumentError` for a code outside the closed table."
  @spec doc_of(code()) :: String.t()
  def doc_of(:not_admitted),
    do:
      "The engine evaluated the admission steps and refused the input: at least one step (SHACL, N3, RDFS, OWL-RL, hooks) did not admit it."

  def doc_of(:plan_refused),
    do:
      "The engine\'s plan step refused: the submitted plan violates a precondition or goal it can verify against the data."

  def doc_of(:receipt_required),
    do:
      "A require_receipt step found no receipt for the required step, so the transition has no receipted admission behind it."

  def doc_of(:lease_refused),
    do:
      "The engine refused the supplied lease: it is unsigned, expired, outside the allowed clock skew, or signed by an untrusted key."

  def doc_of(:resource_limit),
    do:
      "The engine hit a resource limit (input size, fuel, or memory) before it could decide; nothing was admitted or refused."

  def doc_of(:policy_refused),
    do:
      "The engine refused the request under its policy: the requested authority ceiling or operation is not permitted."

  def doc_of(:engine_refused),
    do:
      "The engine refused the request for a structural reason (malformed op, data, or steps) reported under its error kind."

  def doc_of(:engine_unclassified),
    do:
      "The engine returned a refusal variant this library does not know; it is carried verbatim and classified unsupported rather than guessed."

  def doc_of(:wasm_not_vendored),
    do:
      "No GraphLaw WASM binary exists at the resolved path; run mix ash_graphlaw.vendor to fetch the pinned release asset."

  def doc_of(:wasm_unreadable), do: "The GraphLaw WASM file exists at the resolved path but could not be read."
  def doc_of(:wasm_invalid), do: "The bytes at the WASM path do not compile as a WebAssembly module."

  def doc_of(:wasm_digest_mismatch),
    do:
      "The sha256 of the WASM bytes differs from the pinned digest, so the module is not the admitted GraphLaw release."

  def doc_of(:wasm_import_surface_mismatch),
    do:
      "The module imports something other than the wasi_snapshot_preview1 surface, so it is not the pinned GraphLaw shape."

  def doc_of(:wasm_missing_export), do: "The module lacks a required export (gl_alloc, gl_call, gl_free, or memory)."

  def doc_of(:abi_version_mismatch),
    do: "The engine reports an ABI version different from the version this library was built for."

  def doc_of(:instantiation_failed),
    do: "The WASM module passed admission but could not be instantiated by the runtime."

  def doc_of(:abi_failure),
    do:
      "A GraphLaw ABI call violated its contract, for example a bad pointer or a failed allocation; the instance is recycled."

  def doc_of(:call_trapped), do: "The WASM call trapped while executing; the instance is recycled."
  def doc_of(:call_exited), do: "The WASM program exited during the call; the instance is recycled."
  def doc_of(:call_timeout), do: "The call did not finish within the configured timeout_ms."
  def doc_of(:saturated), do: "The host queue is full (max_queue), so the request was shed instead of waiting."
  def doc_of(:host_not_started), do: "No GraphLaw host process is running under the requested server name."
  def doc_of(:fuel_exhausted), do: "The call used up its fuel budget before the engine returned."

  def doc_of(:invalid_encoding),
    do: "The request contained a string that is not valid UTF-8 and was refused before reaching the engine."

  def doc_of(:invalid_json), do: "A request could not be encoded as JSON, or an engine response was not valid JSON."
  def doc_of(:malformed_response), do: "The engine response was valid JSON but lacked the expected envelope fields."
  def doc_of(:unknown_admission), do: "The named admission is not declared in the resource\'s graphlaw section."
  def doc_of(:duplicate_admission), do: "Two admissions in one resource share the same name."

  def doc_of(:missing_law_module),
    do: "An admission uses a step that needs a payload but declares no law module, so it would admit vacuously."

  def doc_of(:invalid_runtime_option),
    do: "A graphlaw runtime option is out of range: timeout_ms must be positive and max_skew_secs non-negative."

  def doc_of(:invalid_trusted_key),
    do: "A trusted key is not a 64-character hexadecimal public key, so lease signatures cannot be checked against it."

  def doc_of(:ceiling_unmet),
    do:
      "The lease in the changeset context does not reach the ceiling the admission requires; refused before the engine is called."

  def doc_of(:projection_failed), do: "The projection module could not produce N-Triples data for the subject."
  def doc_of(:law_module_failed), do: "The law module raised or returned a value that is not a list of step maps."

  def doc_of(:unsupported_step),
    do: "The admission step is not supported by this library version or by the pinned engine release."

  def doc_of(other), do: raise(ArgumentError, "unknown refusal code: #{inspect(other)}")

  @doc """
  Builds a refusal for `code`, filling `class` and `broken_term` from the closed table.

  A nil or empty `message` defaults to the code's meaning (`doc_of/1`). Raises
  `ArgumentError` for a code outside the closed table.
  """
  @spec new(code(), String.t() | nil, map()) :: t()
  def new(code, message \\ nil, details \\ %{}) when is_map(details) do
    %__MODULE__{
      code: code,
      class: class_of(code),
      broken_term: broken_term_of(code),
      message: if(is_binary(message) and message != "", do: message, else: doc_of(code)),
      details: details
    }
  end

  @doc """
  Maps an engine error map (string keys, as decoded from the engine response) onto a refusal.

  `error_map["details"]["code"]` selects a specific code (`NotAdmitted`, `PlanRefused`,
  `ReceiptRequired`, `LeaseRefused`, `ResourceLimit`, `PolicyRefused`). Without one, an
  engine `kind` maps to `:engine_refused` with the original kind kept in `:kind`. A detail
  code this library does not know, or a payload with no usable kind, maps to
  `:engine_unclassified`. Never raises.
  """
  @spec from_engine(term(), map()) :: t()
  def from_engine(error_map, details_map \\ %{})

  def from_engine(error_map, details_map) when is_map(error_map) and is_map(details_map) do
    error_details = with_map(Map.get(error_map, "details"))
    kind = string_or_nil(Map.get(error_map, "kind"))
    engine_code = Map.get(error_details, "code", Map.get(details_map, "code"))
    code = engine_code_to_code(engine_code, kind)

    refusal = new(code, string_or_nil(Map.get(error_map, "message")), Map.merge(error_details, details_map))

    %{
      refusal
      | kind: kind,
        engine: string_or_nil(Map.get(error_map, "engine", Map.get(details_map, "engine"))),
        dialect: string_or_nil(Map.get(error_map, "dialect", Map.get(details_map, "dialect")))
    }
  end

  def from_engine(other, details_map) do
    details = if is_map(details_map), do: details_map, else: %{}
    new(:engine_unclassified, nil, Map.put(details, "raw", inspect(other, limit: 20, printable_limit: 256)))
  end

  @spec engine_code_to_code(term(), String.t() | nil) :: code()
  defp engine_code_to_code(engine_code, kind) when is_binary(engine_code) do
    case Map.fetch(@engine_codes, engine_code) do
      {:ok, code} -> code
      :error -> kind_to_code(kind)
    end
  end

  defp engine_code_to_code(nil, kind), do: kind_to_code(kind)
  defp engine_code_to_code(_engine_code, _kind), do: :engine_unclassified

  defp kind_to_code(kind) when kind in @engine_kinds, do: :engine_refused
  defp kind_to_code(_kind), do: :engine_unclassified

  defp with_map(value) when is_map(value), do: value
  defp with_map(_value), do: %{}

  defp string_or_nil(value) when is_binary(value), do: value
  defp string_or_nil(_value), do: nil

  @impl true
  def message(%__MODULE__{message: message}) when is_binary(message), do: message
  def message(%__MODULE__{code: code}) when is_atom(code) and not is_nil(code), do: "GraphLaw refused: #{code}"
  def message(_refusal), do: "GraphLaw refused"
end
