# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.
# UNSUPPORTED(generator-capability): values/1 hand-adjusted — Elixir 1.20's type checker rejects
# `Map.get(@enums, enum, [])` when the generated `@enums` literal is empty ("the map empty_map()
# does not have all required keys"); the guard-based form below is behaviorally identical for
# every generated map content. Upstream fix belongs in the graphlaw-ash-capability-pack template.

defmodule AshGraphLaw.Model.Enums do
  @moduledoc ~S"""
  Informational values of the named model enums (fields typed `enum:<Name>`).

  Lists are advisory: decoding never rejects a value outside its list, and `member?/2` is a
  convenience that grants no authority.
  """

  @enums %{}

  @doc "Every enum name mapped to its ordered informational values."
  @spec all() :: %{optional(String.t()) => [String.t()]}
  def all, do: @enums

  @doc "The informational values of one enum, or `[]` for an unknown enum."
  @spec values(String.t()) :: [String.t()]
  def values(enum), do: :maps.get(enum, @enums, [])

  @doc "True when `value` is one of the informational values of `enum`."
  @spec member?(String.t(), term()) :: boolean()
  def member?(enum, value), do: value in values(enum)
end
