# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Model.Enums do
  @moduledoc ~S"""
  Informational values of the named model enums (fields typed `enum:<Name>`).

  Lists are advisory: decoding never rejects a value outside its list, and `member?/2` is a
  convenience that grants no authority.
  """

  @enums %{}

  @doc "Every enum name mapped to its ordered informational values."
  @spec all() :: %{optional(String.t()) => [String.t()]}
  def all, do: @enums

  @doc "The informational values of one enum, or `[]` for an unknown enum."
  @spec values(String.t()) :: [String.t()]
  def values(enum), do: Map.get(@enums, enum, [])

  @doc "True when `value` is one of the informational values of `enum`."
  @spec member?(String.t(), term()) :: boolean()
  def member?(enum, value), do: value in values(enum)
end
