# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule Mix.Tasks.AshGraphlaw.VendorDownloadTest do
  @moduledoc """
  The download half of `mix ash_graphlaw.vendor`, against a REAL local TLS server.

  The task fetches over HTTPS with `verify_peer`, the system trust store and a hostname check, and
  keeps the bytes only when their SHA-256 equals the manifest pin. Here:

    * a private CA and a leaf certificate for `127.0.0.1` are generated by real `openssl` subprocesses;
    * that CA (and nothing else) is loaded as the trust store with
      `:public_key.cacerts_load/1`, so the task's real `:httpc` client verifies a real TLS chain;
    * a real `:ssl` listener serves the scripted responses (200, 302/301 redirects, a redirect
      loop, a redirect without `Location`, 404, foreign bytes).

  Nothing is downloaded from the network and the real `priv/graphlaw` is never touched. The trust
  store and the working directory are process-global, so this module is `async: false` and always
  restores both.
  """

  # UNSUPPORTED(generator-capability): hand-written Chicago test; no mocks, no stubs.
  use ExUnit.Case, async: false

  alias AshGraphLaw.Test.WasmFixtures
  alias Mix.Tasks.AshGraphlaw.Vendor

  @good WasmFixtures.admissible_surface()
  @bad WasmFixtures.foreign_imports()

  # -- a real TLS server ---------------------------------------------------------------

  defmodule Server do
    @moduledoc false

    # `routes` maps a request path to `(port -> {status, headers, body})`.
    def start(routes, certfile, keyfile, owner) do
      {:ok, listen} =
        :ssl.listen(0,
          certfile: String.to_charlist(certfile),
          keyfile: String.to_charlist(keyfile),
          active: false,
          mode: :binary,
          reuseaddr: true,
          versions: [:"tlsv1.3", :"tlsv1.2"]
        )

      {:ok, {_addr, port}} = :ssl.sockname(listen)
      pid = spawn_link(fn -> accept_loop(listen, port, routes, owner) end)
      {listen, pid, port}
    end

    def stop({listen, pid, _port}) do
      Process.unlink(pid)
      Process.exit(pid, :kill)
      :ssl.close(listen)
    end

    defp accept_loop(listen, port, routes, owner) do
      case :ssl.transport_accept(listen) do
        {:ok, socket} ->
          pid = spawn(fn -> serve(socket, port, routes, owner) end)
          _ = :ssl.controlling_process(socket, pid)
          accept_loop(listen, port, routes, owner)

        {:error, _closed} ->
          :ok
      end
    end

    defp serve(socket, port, routes, owner) do
      with {:ok, socket} <- :ssl.handshake(socket, 5_000),
           {:ok, request} <- read_request(socket, "") do
        [request_line | header_lines] = String.split(request, "\r\n")
        ["GET", path | _] = String.split(request_line, " ")
        send(owner, {:server_saw, path, header_lines})

        {status, headers, body} =
          case Map.fetch(routes, path) do
            {:ok, route} -> route.(port)
            :error -> {404, [], "not found"}
          end

        :ssl.send(socket, response(status, headers, body))
        :ssl.close(socket)
      else
        _handshake_or_read_failed -> :ok
      end
    end

    defp read_request(socket, acc) do
      if String.contains?(acc, "\r\n\r\n") do
        {:ok, acc}
      else
        case :ssl.recv(socket, 0, 5_000) do
          {:ok, data} -> read_request(socket, acc <> data)
          error -> error
        end
      end
    end

    defp response(status, headers, body) do
      head =
        ["HTTP/1.1 #{status} X", "content-length: #{byte_size(body)}", "connection: close"] ++
          Enum.map(headers, fn {k, v} -> "#{k}: #{v}" end)

      Enum.join(head, "\r\n") <> "\r\n\r\n" <> body
    end
  end

  # -- fixtures ------------------------------------------------------------------------

  setup_all do
    dir = Path.join(System.tmp_dir!(), "agl-vendor-tls-#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    ca = Path.join(dir, "ca.pem")
    ca_key = Path.join(dir, "ca.key")
    cert = Path.join(dir, "cert.pem")
    key = Path.join(dir, "key.pem")
    csr = Path.join(dir, "leaf.csr")
    ext = Path.join(dir, "leaf.ext")
    File.write!(ext, "subjectAltName=IP:127.0.0.1,DNS:localhost\nbasicConstraints=CA:FALSE\n")

    # a private CA and a leaf certificate it signs: the server sends only the leaf, the client
    # trusts only the CA, exactly the shape of a real deployment.
    steps = [
      [
        "req",
        "-x509",
        "-newkey",
        "rsa:2048",
        "-nodes",
        "-keyout",
        ca_key,
        "-out",
        ca,
        "-days",
        "2",
        "-subj",
        "/CN=agl-test-ca"
      ],
      ["req", "-newkey", "rsa:2048", "-nodes", "-keyout", key, "-out", csr, "-subj", "/CN=localhost"],
      [
        "x509",
        "-req",
        "-in",
        csr,
        "-CA",
        ca,
        "-CAkey",
        ca_key,
        "-CAcreateserial",
        "-out",
        cert,
        "-days",
        "2",
        "-extfile",
        ext
      ]
    ]

    for args <- steps do
      {out, status} = System.cmd("openssl", args, stderr_to_stdout: true)
      assert status == 0, "openssl #{hd(args)} failed: #{out}"
    end

    on_exit(fn -> File.rm_rf!(dir) end)
    %{cert: cert, key: key, ca: ca}
  end

  setup ctx do
    Mix.shell(Mix.Shell.Process)

    dir = Path.join(System.tmp_dir!(), "agl-vendor-dl-#{System.unique_integer([:positive])}")
    priv = Path.join(dir, "priv/graphlaw")
    File.mkdir_p!(priv)

    cwd = File.cwd!()
    File.cd!(dir)
    :public_key.cacerts_clear()

    routes = %{
      "/ok" => fn _port -> {200, [], @good} end,
      "/redirect" => fn _port -> {302, [{"location", "/ok"}], ""} end,
      "/redirect-absolute" => fn port -> {301, [{"location", "https://127.0.0.1:#{port}/ok"}], ""} end,
      "/loop" => fn _port -> {302, [{"location", "/loop"}], ""} end,
      "/no-location" => fn _port -> {302, [], ""} end,
      "/missing" => fn _port -> {404, [], "nope"} end,
      "/foreign" => fn _port -> {200, [], @bad} end
    }

    server = Server.start(routes, ctx.cert, ctx.key, self())
    {_listen, _pid, port} = server

    on_exit(fn ->
      Server.stop(server)
      :public_key.cacerts_clear()
      File.cd!(cwd)
      Mix.shell(Mix.Shell.IO)
      File.rm_rf!(dir)
    end)

    %{dir: dir, priv: priv, target: Path.join(priv, "graphlaw.wasm"), port: port}
  end

  defp trust!(ctx), do: :ok = :public_key.cacerts_load(String.to_charlist(ctx.ca))

  defp write_manifest!(priv, url, pin \\ WasmFixtures.sha256(@good)) do
    manifest = %{
      "schema" => "ash_graphlaw.graphlaw.manifest/v1",
      "artifact" => %{"file" => "graphlaw.wasm", "sha256" => pin, "url" => url}
    }

    File.write!(Path.join(priv, "MANIFEST.json"), Jason.encode!(manifest))
  end

  defp url(port, path), do: "https://127.0.0.1:#{port}#{path}"

  defp info_lines(acc \\ []) do
    receive do
      {:mix_shell, :info, [line]} -> info_lines([line | acc])
    after
      0 -> Enum.reverse(acc)
    end
  end

  # -- positive controls ---------------------------------------------------------------

  describe "with the server certificate trusted" do
    setup ctx do
      trust!(ctx)
      :ok
    end

    test "positive control: a 200 whose sha256 is the pin is installed byte for byte", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/ok"))

      Vendor.run([])

      assert File.read!(ctx.target) == @good
      assert Path.wildcard(Path.join(ctx.priv, "*.partial-*")) == []
      assert Enum.any?(info_lines(), &String.starts_with?(&1, "downloading https://127.0.0.1:"))
      assert_received {:server_saw, "/ok", headers}
      assert Enum.any?(headers, &(&1 == "user-agent: ash_graphlaw-vendor"))
      Vendor.run(["--check"])
    end

    test "a relative redirect is followed and the final body is admitted", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/redirect"))

      Vendor.run([])

      assert File.read!(ctx.target) == @good
      assert_received {:server_saw, "/redirect", _}
      assert_received {:server_saw, "/ok", _}
    end

    test "an absolute redirect is followed too", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/redirect-absolute"))
      Vendor.run([])
      assert File.read!(ctx.target) == @good
    end

    test "a redirect loop is cut after a bounded number of hops and nothing is kept", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/loop"))

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*too_many_redirects/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
    end

    test "a redirect without a Location header is refused", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/no-location"))

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*redirect_without_location/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
    end

    test "a non-200 answer is refused with its status", ctx do
      write_manifest!(ctx.priv, url(ctx.port, "/missing"))

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*http_status.*404/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
    end

    test "foreign bytes over a valid TLS session are rejected by the pin, and a vendored engine survives", ctx do
      # positive control first: the pinned bytes are vendored from /ok
      write_manifest!(ctx.priv, url(ctx.port, "/ok"))
      Vendor.run([])
      assert File.read!(ctx.target) == @good

      write_manifest!(ctx.priv, url(ctx.port, "/foreign"))

      assert_raise Mix.Error, ~r/\[wasm_digest_mismatch\].*any vendored engine left untouched/s, fn ->
        Vendor.run([])
      end

      assert File.read!(ctx.target) == @good
      assert Path.wildcard(Path.join(ctx.priv, "*.partial-*")) == []
    end

    test "a connection that cannot be made is refused as wasm_unreadable", ctx do
      {:ok, probe} = :gen_tcp.listen(0, [])
      {:ok, free_port} = :inet.port(probe)
      :gen_tcp.close(probe)

      write_manifest!(ctx.priv, url(free_port, "/ok"))

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*download failed/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
    end
  end

  describe "transport policy" do
    test "a plain http URL is refused before any connection is made", ctx do
      write_manifest!(ctx.priv, "http://127.0.0.1:#{ctx.port}/ok")

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*https_required/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
      refute_received {:server_saw, _, _}
    end

    test "a file URL is not a download source", ctx do
      write_manifest!(ctx.priv, "file:///etc/hosts")
      assert_raise Mix.Error, ~r/https_required/, fn -> Vendor.run([]) end
    end

    test "a server whose certificate is not in the trust store is refused (verify_peer is on)", ctx do
      # the server is the same one that succeeded above; only the trust store differs
      write_manifest!(ctx.priv, url(ctx.port, "/ok"))

      assert_raise Mix.Error, ~r/\[wasm_unreadable\].*download failed/s, fn -> Vendor.run([]) end
      refute File.exists?(ctx.target)
      refute_received {:server_saw, "/ok", _}
    end
  end
end
