# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.API do
  @moduledoc ~S"""
  The complete typed GraphLaw capability API.

  One function per registry operation (`14` in registry `sha256:8f3ef15bad35fc095e4a832b4cca945414e90152c485dc5a5a92d2ff0f804e16`), each
  `(args, opts \\ [])`:

  - `op(args, opts)` returns `{:ok, result}` or `{:error, %AshGraphLaw.Refusal{}}`.
  - `op!(args, opts)` returns the result or raises `AshGraphLaw.Error.Refused`.

  `args` is a keyword list or map with atom or string snake_case keys; `opts` are the options of
  `AshGraphLaw.call/2` (server, timeouts, fuel). Every function runs on the real engine, and no
  supported operation needs `AshGraphLaw.call/2` directly. `run/3` dispatches by wire name and
  refuses an unknown name with `:unknown_capability`.

  Results are observations. Semantic success is not standing, and no result grants authority.
  """

  alias AshGraphLaw.Capability.Registry
  alias AshGraphLaw.Error.Refused
  alias AshGraphLaw.Refusal

  alias AshGraphLaw.Capability.Canonical
  alias AshGraphLaw.Capability.Capabilities
  alias AshGraphLaw.Capability.Convert
  alias AshGraphLaw.Capability.Datalog
  alias AshGraphLaw.Capability.Entail
  alias AshGraphLaw.Capability.Hooks
  alias AshGraphLaw.Capability.Law
  alias AshGraphLaw.Capability.N3
  alias AshGraphLaw.Capability.Parse
  alias AshGraphLaw.Capability.Policy
  alias AshGraphLaw.Capability.Shacl
  alias AshGraphLaw.Capability.Shex
  alias AshGraphLaw.Capability.Sniff
  alias AshGraphLaw.Capability.Sparql

  @typedoc "Request arguments: a keyword list or a map with atom or string snake_case keys."
  @type args :: AshGraphLaw.Capability.args()

  @doc """
  Runs the capability named `op_name` (a wire name from `AshGraphLaw.Capability.Registry.names/0`).

  Refuses with `:unknown_capability` when the registry has no such capability.
  """
  @spec run(String.t(), args(), keyword()) :: {:ok, term()} | {:error, Refusal.t()}
  def run(op_name, args, opts \\ []) when is_binary(op_name) do
    case Registry.module_for(op_name) do
      {:ok, module} ->
        module.run(args, opts)

      :error ->
        {:error,
         Refusal.build(:unknown_capability, "unknown capability #{inspect(op_name)}", %{
           "op" => op_name
         })}
    end
  end

  @doc ~S"""
  Runs the typed `capabilities` capability: Report ABI version, crate version, semantic authorities, dialects, ops and registry digests.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Capabilities`) or `{:error, refusal}`.
  """
  @spec capabilities(args(), keyword()) :: {:ok, Capabilities.t()} | {:error, Refusal.t()}
  def capabilities(args, opts \\ []), do: Capabilities.run(args, opts)

  @doc ~S"""
  Like `capabilities/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec capabilities!(args(), keyword()) :: Capabilities.t()
  def capabilities!(args, opts \\ []) do
    case capabilities(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `sniff` capability: Route text to a dialect and owning engine without parsing it.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Sniff`) or `{:error, refusal}`.
  """
  @spec sniff(args(), keyword()) :: {:ok, Sniff.t()} | {:error, Refusal.t()}
  def sniff(args, opts \\ []), do: Sniff.run(args, opts)

  @doc ~S"""
  Like `sniff/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec sniff!(args(), keyword()) :: Sniff.t()
  def sniff!(args, opts \\ []) do
    case sniff(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `parse` capability: Parse text with the owning engine; counts quads or validates syntax.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Parse`) or `{:error, refusal}`.
  """
  @spec parse(args(), keyword()) :: {:ok, Parse.t()} | {:error, Refusal.t()}
  def parse(args, opts \\ []), do: Parse.run(args, opts)

  @doc ~S"""
  Like `parse/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec parse!(args(), keyword()) :: Parse.t()
  def parse!(args, opts \\ []) do
    case parse(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `convert` capability: Serialize parsed RDF text into another RDF dialect.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Convert`) or `{:error, refusal}`.
  """
  @spec convert(args(), keyword()) :: {:ok, Convert.t()} | {:error, Refusal.t()}
  def convert(args, opts \\ []), do: Convert.run(args, opts)

  @doc ~S"""
  Like `convert/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec convert!(args(), keyword()) :: Convert.t()
  def convert!(args, opts \\ []) do
    case convert(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `canonical` capability: Canonicalize a dataset to N-Quads and return its content-addressed id.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Canonical`) or `{:error, refusal}`.
  """
  @spec canonical(args(), keyword()) :: {:ok, Canonical.t()} | {:error, Refusal.t()}
  def canonical(args, opts \\ []), do: Canonical.run(args, opts)

  @doc ~S"""
  Like `canonical/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec canonical!(args(), keyword()) :: Canonical.t()
  def canonical!(args, opts \\ []) do
    case canonical(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `sparql` capability: Evaluate a SPARQL query over a dataset.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Sparql`) or `{:error, refusal}`.
  """
  @spec sparql(args(), keyword()) :: {:ok, Sparql.t()} | {:error, Refusal.t()}
  def sparql(args, opts \\ []), do: Sparql.run(args, opts)

  @doc ~S"""
  Like `sparql/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec sparql!(args(), keyword()) :: Sparql.t()
  def sparql!(args, opts \\ []) do
    case sparql(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `shacl` capability: Validate a dataset against SHACL shapes.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Shacl`) or `{:error, refusal}`.
  """
  @spec shacl(args(), keyword()) :: {:ok, Shacl.t()} | {:error, Refusal.t()}
  def shacl(args, opts \\ []), do: Shacl.run(args, opts)

  @doc ~S"""
  Like `shacl/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec shacl!(args(), keyword()) :: Shacl.t()
  def shacl!(args, opts \\ []) do
    case shacl(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `shex` capability: Validate a dataset against a ShEx schema and shape map.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Shex`) or `{:error, refusal}`.
  """
  @spec shex(args(), keyword()) :: {:ok, Shex.t()} | {:error, Refusal.t()}
  def shex(args, opts \\ []), do: Shex.run(args, opts)

  @doc ~S"""
  Like `shex/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec shex!(args(), keyword()) :: Shex.t()
  def shex!(args, opts \\ []) do
    case shex(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `n3` capability: Run bounded Notation3 forward reasoning over a document.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.N3`) or `{:error, refusal}`.
  """
  @spec n3(args(), keyword()) :: {:ok, N3.t()} | {:error, Refusal.t()}
  def n3(args, opts \\ []), do: N3.run(args, opts)

  @doc ~S"""
  Like `n3/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec n3!(args(), keyword()) :: N3.t()
  def n3!(args, opts \\ []) do
    case n3(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `entail` capability: Materialize an entailment regime over a dataset.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Entail`) or `{:error, refusal}`.
  """
  @spec entail(args(), keyword()) :: {:ok, Entail.t()} | {:error, Refusal.t()}
  def entail(args, opts \\ []), do: Entail.run(args, opts)

  @doc ~S"""
  Like `entail/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec entail!(args(), keyword()) :: Entail.t()
  def entail!(args, opts \\ []) do
    case entail(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `datalog` capability: Evaluate Datalog rules over triple facts to a fixpoint.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Datalog`) or `{:error, refusal}`.
  """
  @spec datalog(args(), keyword()) :: {:ok, Datalog.t()} | {:error, Refusal.t()}
  def datalog(args, opts \\ []), do: Datalog.run(args, opts)

  @doc ~S"""
  Like `datalog/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec datalog!(args(), keyword()) :: Datalog.t()
  def datalog!(args, opts \\ []) do
    case datalog(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `hooks` capability: Materialize a knowledge-hook pack over a dataset.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Hooks`) or `{:error, refusal}`.
  """
  @spec hooks(args(), keyword()) :: {:ok, Hooks.t()} | {:error, Refusal.t()}
  def hooks(args, opts \\ []), do: Hooks.run(args, opts)

  @doc ~S"""
  Like `hooks/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec hooks!(args(), keyword()) :: Hooks.t()
  def hooks!(args, opts \\ []) do
    case hooks(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `law` capability: Run an ordered chain of law steps with receipts and optional lease authorization.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Law`) or `{:error, refusal}`.
  """
  @spec law(args(), keyword()) :: {:ok, Law.t()} | {:error, Refusal.t()}
  def law(args, opts \\ []), do: Law.run(args, opts)

  @doc ~S"""
  Like `law/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec law!(args(), keyword()) :: Law.t()
  def law!(args, opts \\ []) do
    case law(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end

  @doc ~S"""
  Runs the typed `policy` capability: Admit a FOND policy as strong-cyclic against a planning problem.

  Returns `{:ok, result}` (see `AshGraphLaw.Capability.Policy`) or `{:error, refusal}`.
  """
  @spec policy(args(), keyword()) :: {:ok, Policy.t()} | {:error, Refusal.t()}
  def policy(args, opts \\ []), do: Policy.run(args, opts)

  @doc ~S"""
  Like `policy/2` but returns the result and raises `AshGraphLaw.Error.Refused` on a refusal.
  """
  @spec policy!(args(), keyword()) :: Policy.t()
  def policy!(args, opts \\ []) do
    case policy(args, opts) do
      {:ok, result} -> result
      {:error, %Refusal{} = refusal} -> raise Refused, refusal: refusal
    end
  end
end
