# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.Convert do
  @moduledoc ~S"""
  Typed `convert` capability (registry order 4).

  Serialize parsed RDF text into another RDF dialect.

  Request fields, response variants and the refusal vocabulary of this operation are declared in
  the GraphLaw capability registry and projected here without per-operation hand-written code.
  `run/2` builds the request, calls the real engine through `AshGraphLaw.call/2` (same options as
  `call/2`: server, timeouts, fuel) and decodes the response into
  `AshGraphLaw.Result.Convert`.

  ## Example

      {:ok, request} = AshGraphLaw.Capability.Convert.build_request([text: "...", to: "..."])
      request["op"]
      #=> "convert"

  See `AshGraphLaw.Capability.Registry.op/1` for the full field, variant and refusal metadata.
  """

  @behaviour AshGraphLaw.Capability

  alias AshGraphLaw.Capability.Coerce
  alias AshGraphLaw.Capability.Decode
  alias AshGraphLaw.Refusal
  alias AshGraphLaw.Telemetry

  alias AshGraphLaw.Result.Convert, as: Result

  @op "convert"

  @request_fields [
    %{
      name: "text",
      order: 1,
      type: "string",
      required: true,
      nullable: false,
      doc: "Text to convert.",
      enum: nil,
      default: nil
    },
    %{
      name: "to",
      order: 2,
      type: "string",
      required: true,
      nullable: false,
      doc: "Target RDF dialect name.",
      enum: nil,
      default: nil
    },
    %{
      name: "dialect",
      order: 3,
      type: "string",
      required: false,
      nullable: true,
      doc: "Source dialect name; sniffed when omitted.",
      enum: nil,
      default: nil
    },
    %{
      name: "hint",
      order: 4,
      type: "string",
      required: false,
      nullable: true,
      doc: "File extension or name hint for sniffing.",
      enum: nil,
      default: nil
    },
    %{
      name: "base",
      order: 5,
      type: "string",
      required: false,
      nullable: true,
      doc: "Base IRI.",
      enum: nil,
      default: nil
    }
  ]

  @response_fields [
    %{
      name: "text",
      order: 1,
      type: "string",
      required: true,
      nullable: false,
      doc: "Serialized output.",
      enum: nil,
      default: nil
    },
    %{
      name: "id",
      order: 2,
      type: "string",
      required: true,
      nullable: false,
      doc: "Content-addressed id of the source state.",
      enum: nil,
      default: nil
    }
  ]

  @typedoc "The decoded result of a successful `convert` call."
  @type t :: Result.t()

  @doc "The wire name of the operation."
  @impl true
  @spec op() :: String.t()
  def op, do: @op

  @doc """
  The registry fields of this operation: `:request` for the request fields, `:response` for the
  union of the response fields of all variants (first-seen order, no enum lists).
  """
  @spec fields(:request | :response) :: [AshGraphLaw.Capability.Registry.field()]
  def fields(:request), do: @request_fields
  def fields(:response), do: @response_fields

  @doc """
  Builds the engine request for this operation from `args` (a keyword list or map).

  Refuses with `:invalid_capability_request` on unknown keys, missing required fields or type
  mismatches. Enum lists are informational and never enforced. The `"op"` key is injected here.
  """
  @impl true
  @spec build_request(AshGraphLaw.Capability.args()) :: {:ok, map()} | {:error, Refusal.t()}
  def build_request(args) do
    with {:ok, request} <- Coerce.request(@op, @request_fields, args) do
      {:ok, Map.put(request, "op", @op)}
    end
  end

  @doc """
  Decodes an engine response for this operation into its result struct. Never raises on
  unexpected shapes; a non-map response refuses with `:capability_response_undecodable`.
  """
  @impl true
  @spec decode(term()) :: {:ok, t()} | {:error, Refusal.t()}
  def decode(response) do
    with {:ok, map} <- Decode.ensure_map(response) do
      {:ok, Result.from_map(map)}
    end
  end

  @doc """
  Builds the request, runs it on the engine and decodes the response inside a
  `[:ash_graphlaw, :capability, ...]` telemetry span. `opts` are the options of `AshGraphLaw.call/2`.
  """
  @impl true
  @spec run(AshGraphLaw.Capability.args(), keyword()) :: {:ok, t()} | {:error, Refusal.t()}
  def run(args, opts \\ []) do
    Telemetry.capability(@op, opts, fn ->
      with {:ok, request} <- build_request(args),
           {:ok, response} <- AshGraphLaw.call(request, opts) do
        decode(response)
      end
    end)
  end
end
