# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.Law do
  @moduledoc ~S"""
  Typed `law` capability (registry order 13).

  Run an ordered chain of law steps with receipts and optional lease authorization.

  Request fields, response variants and the refusal vocabulary of this operation are declared in
  the GraphLaw capability registry and projected here without per-operation hand-written code.
  `run/2` builds the request, calls the real engine through `AshGraphLaw.call/2` (same options as
  `call/2`: server, timeouts, fuel) and decodes the response into
  `AshGraphLaw.Admitted`.

  ## Example

      {:ok, request} = AshGraphLaw.Capability.Law.build_request([data: "...", steps: []])
      request["op"]
      #=> "law"

  See `AshGraphLaw.Capability.Registry.op/1` for the full field, variant and refusal metadata.
  """

  @behaviour AshGraphLaw.Capability

  alias AshGraphLaw.Capability.Coerce
  alias AshGraphLaw.Capability.Decode
  alias AshGraphLaw.Refusal
  alias AshGraphLaw.Telemetry

  alias AshGraphLaw.Admitted, as: Result

  @op "law"

  @request_fields [
    %{
      name: "data",
      order: 1,
      type: "data_spec",
      required: true,
      nullable: false,
      doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
      enum: nil,
      default: nil
    },
    %{
      name: "steps",
      order: 2,
      type: "list<object>",
      required: true,
      nullable: false,
      doc: "Ordered law steps; see law_steps.",
      enum: nil,
      default: nil
    },
    %{
      name: "signed_lease",
      order: 3,
      type: "object",
      required: false,
      nullable: false,
      doc: "Signed lease {lease, attestation}; verified offline against trusted_keys.",
      enum: nil,
      default: nil
    },
    %{
      name: "lease",
      order: 4,
      type: "object",
      required: false,
      nullable: false,
      doc: "Unsigned lease; refused unless unverified_lease is true.",
      enum: nil,
      default: nil
    },
    %{
      name: "trusted_keys",
      order: 5,
      type: "list<string>",
      required: false,
      nullable: false,
      doc: "Hex Ed25519 public keys trusted to sign leases.",
      enum: nil,
      default: nil
    },
    %{
      name: "max_skew_secs",
      order: 6,
      type: "integer",
      required: false,
      nullable: true,
      doc: "Clock skew tolerance for signed leases in seconds.",
      enum: nil,
      default: nil
    },
    %{
      name: "unverified_lease",
      order: 7,
      type: "boolean",
      required: false,
      nullable: false,
      doc: "Accept an unsigned lease; proves nothing about its issuer.",
      enum: nil,
      default: nil
    },
    %{
      name: "now_unix",
      order: 8,
      type: "integer",
      required: false,
      nullable: false,
      doc: "Caller clock in unix seconds; used only with an unverified lease.",
      enum: nil,
      default: nil
    }
  ]

  @response_fields [
    %{
      name: "states",
      order: 1,
      type: "list<string>",
      required: true,
      nullable: false,
      doc: "State ids after each step, starting with the input.",
      enum: nil,
      default: nil
    },
    %{
      name: "receipts",
      order: 2,
      type: "list<object>",
      required: true,
      nullable: false,
      doc: "Receipts, one per transition.",
      enum: nil,
      default: nil
    },
    %{
      name: "nquads",
      order: 3,
      type: "string",
      required: true,
      nullable: false,
      doc: "Final state as N-Quads.",
      enum: nil,
      default: nil
    }
  ]

  @typedoc "The decoded result of a successful `law` call."
  @type t :: Result.t()

  @doc "The wire name of the operation."
  @impl true
  @spec op() :: String.t()
  def op, do: @op

  @doc """
  The registry fields of this operation: `:request` for the request fields, `:response` for the
  union of the response fields of all variants (first-seen order, no enum lists).
  """
  @spec fields(:request | :response) :: [AshGraphLaw.Capability.Registry.field()]
  def fields(:request), do: @request_fields
  def fields(:response), do: @response_fields

  @doc """
  Builds the engine request for this operation from `args` (a keyword list or map).

  Refuses with `:invalid_capability_request` on unknown keys, missing required fields or type
  mismatches. Enum lists are informational and never enforced. The `"op"` key is injected here.
  """
  @impl true
  @spec build_request(AshGraphLaw.Capability.args()) :: {:ok, map()} | {:error, Refusal.t()}
  def build_request(args) do
    with {:ok, request} <- Coerce.request(@op, @request_fields, args) do
      {:ok, Map.put(request, "op", @op)}
    end
  end

  @doc """
  Decodes an engine response for this operation into its result struct. Never raises on
  unexpected shapes; a non-map response refuses with `:capability_response_undecodable`.
  """
  @impl true
  @spec decode(term()) :: {:ok, t()} | {:error, Refusal.t()}
  def decode(response) do
    with {:ok, map} <- Decode.ensure_map(response) do
      {:ok, Result.from_map(map)}
    end
  end

  @doc """
  Builds the request, runs it on the engine and decodes the response inside a
  `[:ash_graphlaw, :capability, ...]` telemetry span. `opts` are the options of `AshGraphLaw.call/2`.
  """
  @impl true
  @spec run(AshGraphLaw.Capability.args(), keyword()) :: {:ok, t()} | {:error, Refusal.t()}
  def run(args, opts \\ []) do
    Telemetry.capability(@op, opts, fn ->
      with {:ok, request} <- build_request(args),
           {:ok, response} <- AshGraphLaw.call(request, opts) do
        decode(response)
      end
    end)
  end
end
