# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.Limits do
  @moduledoc ~S"""
  Engine resource limits as reported by the GraphLaw capability registry, with the scope each
  limit bounds, its unit and the engine source file that enforces it.

  Limits are observations of the engine release; they are never negotiated by the client.
  """

  @type limit :: %{
          name: atom(),
          value: non_neg_integer(),
          scope: String.t(),
          unit: String.t(),
          source: String.t()
        }

  @limits [
    %{name: :max_atoms_per_field, value: 10000, scope: "", unit: "", source: ""},
    %{name: :max_json_depth, value: 64, scope: "", unit: "", source: ""},
    %{name: :max_plan_actions, value: 1000, scope: "", unit: "", source: ""},
    %{name: :max_policy_entries, value: 100_000, scope: "", unit: "", source: ""},
    %{name: :max_request_bytes, value: 16_777_216, scope: "", unit: "", source: ""},
    %{name: :n3_max_iterations, value: 4000, scope: "", unit: "", source: ""}
  ]

  @doc "Every limit in name order."
  @spec all() :: [limit()]
  def all, do: @limits

  @doc "The limit named `name`, or `:error` for an unknown limit."
  @spec get(atom()) :: {:ok, limit()} | :error
  def get(name) when is_atom(name) do
    case Enum.find(@limits, &(&1.name == name)) do
      nil -> :error
      limit -> {:ok, limit}
    end
  end

  @doc "The limits that bound `scope`."
  @spec in_scope(String.t()) :: [limit()]
  def in_scope(scope), do: Enum.filter(@limits, &(&1.scope == scope))

  @doc "Limit `max_atoms_per_field`."
  @spec max_atoms_per_field() :: non_neg_integer()
  def max_atoms_per_field, do: 10000

  @doc "Limit `max_json_depth`."
  @spec max_json_depth() :: non_neg_integer()
  def max_json_depth, do: 64

  @doc "Limit `max_plan_actions`."
  @spec max_plan_actions() :: non_neg_integer()
  def max_plan_actions, do: 1000

  @doc "Limit `max_policy_entries`."
  @spec max_policy_entries() :: non_neg_integer()
  def max_policy_entries, do: 100_000

  @doc "Limit `max_request_bytes`."
  @spec max_request_bytes() :: non_neg_integer()
  def max_request_bytes, do: 16_777_216

  @doc "Limit `n3_max_iterations`."
  @spec n3_max_iterations() :: non_neg_integer()
  def n3_max_iterations, do: 4000
end
