# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.Registry do
  @moduledoc ~S"""
  The GraphLaw capability registry as compile-time literals.

  Generated from the registry `graphlaw.capability-registry/1` (GraphLaw `26.9.29`, ABI
  `1`). `digest/0` is the registry's own `registry_sha256`; `surface_digest/0` is the
  SHA-256 over the canonical surface document (ABI version, op names, dialect names) that a live
  engine's `capabilities` response can be compared against.

  All maps use atom keys. A field map has the keys `:name :order :type :required :nullable :doc
  :enum :default`; `:enum` is informational and is never enforced client-side.
  """

  @typedoc "One request, response, detail or law-step field."
  @type field :: %{
          name: String.t(),
          order: pos_integer(),
          type: String.t(),
          required: boolean(),
          nullable: boolean(),
          doc: String.t(),
          enum: [String.t()] | nil,
          default: String.t() | integer() | boolean() | nil
        }

  @typedoc "One response variant; an untagged op has exactly one variant with a `nil` tag."
  @type variant :: %{tag: String.t() | nil, tag_field: String.t() | nil, fields: [field()]}

  @typedoc "One wire operation."
  @type op :: %{
          name: String.t(),
          order: pos_integer(),
          summary: String.t(),
          request: [field()],
          responses: [variant()],
          refusal_kinds: [String.t()],
          refusal_codes: [String.t()]
        }

  @typedoc "One serialization dialect."
  @type dialect :: %{
          name: String.t(),
          order: pos_integer(),
          aliases: [String.t()],
          response_name: String.t(),
          media_type: String.t() | nil,
          kind: String.t()
        }

  @typedoc "One step of the `law` operation."
  @type law_step :: %{
          name: String.t(),
          order: pos_integer(),
          ceiling: String.t() | nil,
          fields: [field()]
        }

  @typedoc "One engine refusal detail code (the `details.code` wire values)."
  @type refusal_code :: %{
          code: String.t(),
          order: pos_integer(),
          kind: String.t() | nil,
          fields: [field()]
        }

  @schema "graphlaw.capability-registry/1"
  @graphlaw_version "26.9.29"
  @abi_version 1
  @digest "sha256:8f3ef15bad35fc095e4a832b4cca945414e90152c485dc5a5a92d2ff0f804e16"
  @surface_digest "sha256:fcee74ee068940f9e9879ccd41371807f469d63950c8f63b095117391dbc8e28"

  @names [
    "capabilities",
    "sniff",
    "parse",
    "convert",
    "canonical",
    "sparql",
    "shacl",
    "shex",
    "n3",
    "entail",
    "datalog",
    "hooks",
    "law",
    "policy"
  ]

  @ops [
    %{
      name: "capabilities",
      order: 1,
      summary: "Report ABI version, crate version, semantic authorities, dialects, ops and registry digests.",
      request: [
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "abi",
              order: 1,
              type: "integer",
              required: true,
              nullable: false,
              doc: "ABI revision (legacy alias of abi_version).",
              enum: nil,
              default: nil
            },
            %{
              name: "abi_version",
              order: 2,
              type: "integer",
              required: true,
              nullable: false,
              doc: "ABI revision.",
              enum: nil,
              default: nil
            },
            %{
              name: "crate",
              order: 3,
              type: "string",
              required: true,
              nullable: false,
              doc: "GraphLaw crate version.",
              enum: nil,
              default: nil
            },
            %{
              name: "authorities",
              order: 4,
              type: "list<object>",
              required: true,
              nullable: false,
              doc: "Semantic authority map: {capability, authority, revision}.",
              enum: nil,
              default: nil
            },
            %{
              name: "rdf_dialects",
              order: 5,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "RDF dialect wire names.",
              enum: nil,
              default: nil
            },
            %{
              name: "other_dialects",
              order: 6,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "Non-RDF dialect wire names.",
              enum: nil,
              default: nil
            },
            %{
              name: "ops",
              order: 7,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "ABI op names in registry order.",
              enum: nil,
              default: nil
            },
            %{
              name: "registry_schema",
              order: 8,
              type: "string",
              required: false,
              nullable: false,
              doc: "Registry schema id; absent on engines older than v26.9.29.",
              enum: nil,
              default: nil
            },
            %{
              name: "registry_sha256",
              order: 9,
              type: "string",
              required: false,
              nullable: false,
              doc: "Registry digest; absent on engines older than v26.9.29.",
              enum: nil,
              default: nil
            },
            %{
              name: "surface_sha256",
              order: 10,
              type: "string",
              required: false,
              nullable: false,
              doc: "Surface digest; absent on engines older than v26.9.29.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "sniff",
      order: 2,
      summary: "Route text to a dialect and owning engine without parsing it.",
      request: [
        %{
          name: "text",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Text to route.",
          enum: nil,
          default: nil
        },
        %{
          name: "hint",
          order: 2,
          type: "string",
          required: false,
          nullable: true,
          doc: "File extension or name hint.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "dialect",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Sniffed dialect (Rust variant name).",
              enum: nil,
              default: nil
            },
            %{
              name: "engine",
              order: 2,
              type: "string",
              required: true,
              nullable: false,
              doc: "Owning engine (PurRdf or Eyeron).",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "parse",
      order: 3,
      summary: "Parse text with the owning engine; counts quads or validates syntax.",
      request: [
        %{
          name: "text",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Text to parse.",
          enum: nil,
          default: nil
        },
        %{
          name: "dialect",
          order: 2,
          type: "string",
          required: false,
          nullable: true,
          doc: "Dialect name; sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "hint",
          order: 3,
          type: "string",
          required: false,
          nullable: true,
          doc: "File extension or name hint for sniffing.",
          enum: nil,
          default: nil
        },
        %{
          name: "base",
          order: 4,
          type: "string",
          required: false,
          nullable: true,
          doc: "Base IRI.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "dialect",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Dialect used (Rust variant name).",
              enum: nil,
              default: nil
            },
            %{
              name: "quads",
              order: 2,
              type: "integer",
              required: false,
              nullable: false,
              doc: "Quad count; present for RDF dialects.",
              enum: nil,
              default: nil
            },
            %{
              name: "id",
              order: 3,
              type: "string",
              required: false,
              nullable: false,
              doc: "Content-addressed state id; present for RDF dialects.",
              enum: nil,
              default: nil
            },
            %{
              name: "valid",
              order: 4,
              type: "boolean",
              required: false,
              nullable: false,
              doc: "Syntax validity; present for non-RDF dialects.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "convert",
      order: 4,
      summary: "Serialize parsed RDF text into another RDF dialect.",
      request: [
        %{
          name: "text",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Text to convert.",
          enum: nil,
          default: nil
        },
        %{
          name: "to",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "Target RDF dialect name.",
          enum: nil,
          default: nil
        },
        %{
          name: "dialect",
          order: 3,
          type: "string",
          required: false,
          nullable: true,
          doc: "Source dialect name; sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "hint",
          order: 4,
          type: "string",
          required: false,
          nullable: true,
          doc: "File extension or name hint for sniffing.",
          enum: nil,
          default: nil
        },
        %{
          name: "base",
          order: 5,
          type: "string",
          required: false,
          nullable: true,
          doc: "Base IRI.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "text",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Serialized output.",
              enum: nil,
              default: nil
            },
            %{
              name: "id",
              order: 2,
              type: "string",
              required: true,
              nullable: false,
              doc: "Content-addressed id of the source state.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "canonical",
      order: 5,
      summary: "Canonicalize a dataset to N-Quads and return its content-addressed id.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "id",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Content-addressed state id.",
              enum: nil,
              default: nil
            },
            %{
              name: "nquads",
              order: 2,
              type: "string",
              required: true,
              nullable: false,
              doc: "Canonical N-Quads.",
              enum: nil,
              default: nil
            },
            %{
              name: "quads",
              order: 3,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Quad count.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "sparql",
      order: 6,
      summary: "Evaluate a SPARQL query over a dataset.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "query",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "SPARQL query text.",
          enum: nil,
          default: nil
        },
        %{
          name: "base",
          order: 3,
          type: "string",
          required: false,
          nullable: true,
          doc: "Base IRI.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: "solutions",
          tag_field: "kind",
          fields: [
            %{
              name: "variables",
              order: 1,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "Projected variable names.",
              enum: nil,
              default: nil
            },
            %{
              name: "rows",
              order: 2,
              type: "list<list<term>>",
              required: true,
              nullable: false,
              doc: "Solution rows; null marks an unbound cell.",
              enum: nil,
              default: nil
            }
          ]
        },
        %{
          tag: "graph",
          tag_field: "kind",
          fields: [
            %{
              name: "nquads",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Constructed graph as N-Quads.",
              enum: nil,
              default: nil
            },
            %{
              name: "quads",
              order: 2,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Quad count of the constructed graph.",
              enum: nil,
              default: nil
            }
          ]
        },
        %{
          tag: "boolean",
          tag_field: "kind",
          fields: [
            %{
              name: "value",
              order: 1,
              type: "boolean",
              required: true,
              nullable: false,
              doc: "ASK result.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "shacl",
      order: 7,
      summary: "Validate a dataset against SHACL shapes.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "shapes",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "SHACL shapes graph as Turtle text.",
          enum: nil,
          default: nil
        },
        %{
          name: "base",
          order: 3,
          type: "string",
          required: false,
          nullable: true,
          doc: "Base IRI.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "conforms",
              order: 1,
              type: "boolean",
              required: true,
              nullable: false,
              doc: "True when the data conforms.",
              enum: nil,
              default: nil
            },
            %{
              name: "results",
              order: 2,
              type: "list<object>",
              required: true,
              nullable: false,
              doc: "Validation results: {focus, path, value, severity, component, shape, message}.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "shex",
      order: 8,
      summary: "Validate a dataset against a ShEx schema and shape map.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "schema",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "ShEx schema text.",
          enum: nil,
          default: nil
        },
        %{
          name: "schema_dialect",
          order: 3,
          type: "string",
          required: false,
          nullable: true,
          doc: "Schema syntax.",
          enum: ["shexc", "shexj"],
          default: "shexc"
        },
        %{
          name: "map",
          order: 4,
          type: "string",
          required: true,
          nullable: false,
          doc: "Shape map text.",
          enum: nil,
          default: nil
        },
        %{
          name: "base",
          order: 5,
          type: "string",
          required: false,
          nullable: true,
          doc: "Base IRI.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "conforms",
              order: 1,
              type: "boolean",
              required: true,
              nullable: false,
              doc: "True when every map entry is conformant.",
              enum: nil,
              default: nil
            },
            %{
              name: "entries",
              order: 2,
              type: "list<object>",
              required: true,
              nullable: false,
              doc: "Shape map entries: {node, shape, status, reason}.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "n3",
      order: 9,
      summary: "Run bounded Notation3 forward reasoning over a document.",
      request: [
        %{
          name: "text",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Notation3 document with data and rules.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "derived",
              order: 1,
              type: "any",
              required: true,
              nullable: false,
              doc: "Reasoner output; shape is owned by Eyeron.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["EngineRejected", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "entail",
      order: 10,
      summary: "Materialize an entailment regime over a dataset.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "regime",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "Entailment regime.",
          enum: ["simple", "rdf", "rdfs", "owl-rl", "d"],
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "nquads",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Closure as N-Quads.",
              enum: nil,
              default: nil
            },
            %{
              name: "added",
              order: 2,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Quads added by materialization.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "datalog",
      order: 11,
      summary: "Evaluate Datalog rules over triple facts to a fixpoint.",
      request: [
        %{
          name: "rules",
          order: 1,
          type: "list<object>",
          required: true,
          nullable: false,
          doc: "Rules: {head: [s,p,o], body: [[s,p,o], ...]}; terms starting with ? are variables.",
          enum: nil,
          default: nil
        },
        %{
          name: "facts",
          order: 2,
          type: "list<list<string>>",
          required: true,
          nullable: false,
          doc: "Ground facts as [subject, predicate, object] strings.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "count",
              order: 1,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Number of facts in the fixpoint.",
              enum: nil,
              default: nil
            },
            %{
              name: "facts",
              order: 2,
              type: "list<list<string>>",
              required: true,
              nullable: false,
              doc: "Sorted fixpoint facts as [subject, predicate, object].",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["EngineRejected", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "hooks",
      order: 12,
      summary: "Materialize a knowledge-hook pack over a dataset.",
      request: [
        %{
          name: "pack",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Hook pack as a data spec (kh: vocabulary).",
          enum: nil,
          default: nil
        },
        %{
          name: "data",
          order: 2,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "id",
              order: 1,
              type: "string",
              required: true,
              nullable: false,
              doc: "Content-addressed id of the materialized state.",
              enum: nil,
              default: nil
            },
            %{
              name: "rounds",
              order: 2,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Fixpoint rounds executed.",
              enum: nil,
              default: nil
            },
            %{
              name: "quads",
              order: 3,
              type: "integer",
              required: true,
              nullable: false,
              doc: "Quad count of the materialized state.",
              enum: nil,
              default: nil
            },
            %{
              name: "nquads",
              order: 4,
              type: "string",
              required: true,
              nullable: false,
              doc: "Materialized state as N-Quads.",
              enum: nil,
              default: nil
            },
            %{
              name: "firings",
              order: 5,
              type: "list<object>",
              required: true,
              nullable: false,
              doc: "Hook firings: {hook, round, added, row}.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["ResourceLimit"]
    },
    %{
      name: "law",
      order: 13,
      summary: "Run an ordered chain of law steps with receipts and optional lease authorization.",
      request: [
        %{
          name: "data",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
          enum: nil,
          default: nil
        },
        %{
          name: "steps",
          order: 2,
          type: "list<object>",
          required: true,
          nullable: false,
          doc: "Ordered law steps; see law_steps.",
          enum: nil,
          default: nil
        },
        %{
          name: "signed_lease",
          order: 3,
          type: "object",
          required: false,
          nullable: false,
          doc: "Signed lease {lease, attestation}; verified offline against trusted_keys.",
          enum: nil,
          default: nil
        },
        %{
          name: "lease",
          order: 4,
          type: "object",
          required: false,
          nullable: false,
          doc: "Unsigned lease; refused unless unverified_lease is true.",
          enum: nil,
          default: nil
        },
        %{
          name: "trusted_keys",
          order: 5,
          type: "list<string>",
          required: false,
          nullable: false,
          doc: "Hex Ed25519 public keys trusted to sign leases.",
          enum: nil,
          default: nil
        },
        %{
          name: "max_skew_secs",
          order: 6,
          type: "integer",
          required: false,
          nullable: true,
          doc: "Clock skew tolerance for signed leases in seconds.",
          enum: nil,
          default: nil
        },
        %{
          name: "unverified_lease",
          order: 7,
          type: "boolean",
          required: false,
          nullable: false,
          doc: "Accept an unsigned lease; proves nothing about its issuer.",
          enum: nil,
          default: nil
        },
        %{
          name: "now_unix",
          order: 8,
          type: "integer",
          required: false,
          nullable: false,
          doc: "Caller clock in unix seconds; used only with an unverified lease.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "states",
              order: 1,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "State ids after each step, starting with the input.",
              enum: nil,
              default: nil
            },
            %{
              name: "receipts",
              order: 2,
              type: "list<object>",
              required: true,
              nullable: false,
              doc: "Receipts, one per transition.",
              enum: nil,
              default: nil
            },
            %{
              name: "nquads",
              order: 3,
              type: "string",
              required: true,
              nullable: false,
              doc: "Final state as N-Quads.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["Ambiguous", "EngineRejected", "NotSemanticContent", "ResourceLimit", "Unsupported"],
      refusal_codes: ["LeaseRefused", "NotAdmitted", "PlanRefused", "ReceiptRefused", "ReceiptRequired", "Refused", "ResourceLimit", "UnverifiedLeaseRefused"]
    },
    %{
      name: "policy",
      order: 14,
      summary: "Admit a FOND policy as strong-cyclic against a planning problem.",
      request: [
        %{
          name: "problem",
          order: 1,
          type: "json_or_string",
          required: true,
          nullable: false,
          doc: "Planning problem as a JSON object or JSON text.",
          enum: nil,
          default: nil
        },
        %{
          name: "policy",
          order: 2,
          type: "json_or_string",
          required: true,
          nullable: false,
          doc: "Policy as a JSON object, entries array or JSON text.",
          enum: nil,
          default: nil
        }
      ],
      responses: [
        %{
          tag: nil,
          tag_field: nil,
          fields: [
            %{
              name: "initial_states",
              order: 1,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "Initial states of the problem.",
              enum: nil,
              default: nil
            },
            %{
              name: "reachable",
              order: 2,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "States reachable under the policy.",
              enum: nil,
              default: nil
            },
            %{
              name: "goal_states",
              order: 3,
              type: "list<string>",
              required: true,
              nullable: false,
              doc: "Reachable goal states.",
              enum: nil,
              default: nil
            },
            %{
              name: "entries",
              order: 4,
              type: "list<list<string>>",
              required: true,
              nullable: false,
              doc: "Admitted policy entries as [state, action].",
              enum: nil,
              default: nil
            },
            %{
              name: "ntriples",
              order: 5,
              type: "string",
              required: true,
              nullable: false,
              doc: "Admitted policy as N-Triples.",
              enum: nil,
              default: nil
            }
          ]
        }
      ],
      refusal_kinds: ["EngineRejected", "ResourceLimit", "Unsupported"],
      refusal_codes: ["PolicyRefused", "ResourceLimit"]
    }
  ]

  @ops_by_name Map.new(@ops, fn op -> {op.name, op} end)

  @dialects [
    %{
      name: "turtle",
      order: 1,
      aliases: ["ttl"],
      response_name: "Turtle",
      media_type: "text/turtle",
      kind: "rdf"
    },
    %{
      name: "trig",
      order: 2,
      aliases: [],
      response_name: "TriG",
      media_type: "application/trig",
      kind: "rdf"
    },
    %{
      name: "ntriples",
      order: 3,
      aliases: ["nt"],
      response_name: "NTriples",
      media_type: "application/n-triples",
      kind: "rdf"
    },
    %{
      name: "nquads",
      order: 4,
      aliases: ["nq"],
      response_name: "NQuads",
      media_type: "application/n-quads",
      kind: "rdf"
    },
    %{
      name: "rdfxml",
      order: 5,
      aliases: ["owl", "rdf"],
      response_name: "RdfXml",
      media_type: "application/rdf+xml",
      kind: "rdf"
    },
    %{
      name: "jsonld",
      order: 6,
      aliases: [],
      response_name: "JsonLd",
      media_type: "application/ld+json",
      kind: "rdf"
    },
    %{
      name: "yamlld",
      order: 7,
      aliases: [],
      response_name: "YamlLd",
      media_type: "application/ld+yaml",
      kind: "rdf"
    },
    %{
      name: "trix",
      order: 8,
      aliases: [],
      response_name: "TriX",
      media_type: "application/trix",
      kind: "rdf"
    },
    %{
      name: "hextuples",
      order: 9,
      aliases: ["hext"],
      response_name: "HexTuples",
      media_type: "application/x-hextuples",
      kind: "rdf"
    },
    %{
      name: "n3",
      order: 10,
      aliases: [],
      response_name: "N3",
      media_type: nil,
      kind: "other"
    },
    %{
      name: "sparql",
      order: 11,
      aliases: ["rq"],
      response_name: "Sparql",
      media_type: nil,
      kind: "other"
    },
    %{
      name: "shexc",
      order: 12,
      aliases: ["shex"],
      response_name: "ShExC",
      media_type: nil,
      kind: "other"
    },
    %{
      name: "shexj",
      order: 13,
      aliases: [],
      response_name: "ShExJ",
      media_type: nil,
      kind: "other"
    }
  ]

  @law_steps [
    %{
      name: "shacl",
      order: 1,
      ceiling: "observe",
      fields: [
        %{
          name: "shapes",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "SHACL shapes graph as Turtle text.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      name: "n3",
      order: 2,
      ceiling: "construct",
      fields: [
        %{
          name: "rules",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Notation3 rules text.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      name: "rdfs",
      order: 3,
      ceiling: "construct",
      fields: [
      ]
    },
    %{
      name: "owl-rl",
      order: 4,
      ceiling: "construct",
      fields: [
      ]
    },
    %{
      name: "hooks",
      order: 5,
      ceiling: "construct",
      fields: [
        %{
          name: "pack",
          order: 1,
          type: "data_spec",
          required: true,
          nullable: false,
          doc: "Hook pack as a data spec.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      name: "plan",
      order: 6,
      ceiling: "select",
      fields: [
        %{
          name: "plan",
          order: 1,
          type: "object",
          required: true,
          nullable: false,
          doc: "Plan {actions: [{name, pre, pre_not?, add, del}], goal, goal_not?} with N-Triples strings.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      name: "record-receipts",
      order: 7,
      ceiling: nil,
      fields: [
      ]
    },
    %{
      name: "require-receipt",
      order: 8,
      ceiling: "observe",
      fields: [
        %{
          name: "step_name",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Step whose receipt must already be recorded.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      name: "require-signed-receipt",
      order: 9,
      ceiling: "observe",
      fields: [
        %{
          name: "step_name",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Step whose receipt must carry a valid attestation.",
          enum: nil,
          default: nil
        },
        %{
          name: "trusted_keys",
          order: 2,
          type: "list<string>",
          required: true,
          nullable: false,
          doc: "Hex Ed25519 public keys trusted to attest the receipt.",
          enum: nil,
          default: nil
        }
      ]
    }
  ]

  @refusal_codes [
    %{
      code: "Refused",
      order: 1,
      kind: nil,
      fields: [
        %{
          name: "kind",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Refusal kind of the underlying engine refusal.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "ResourceLimit",
      order: 2,
      kind: "ResourceLimit",
      fields: [
        %{
          name: "limit",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Name of the exceeded limit.",
          enum: nil,
          default: nil
        },
        %{
          name: "observed",
          order: 2,
          type: "integer",
          required: false,
          nullable: false,
          doc: "Observed size; absent for iteration limits.",
          enum: nil,
          default: nil
        },
        %{
          name: "max",
          order: 3,
          type: "integer",
          required: true,
          nullable: false,
          doc: "Configured maximum.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "PlanRefused",
      order: 3,
      kind: "EngineRejected",
      fields: [
        %{
          name: "index",
          order: 1,
          type: "integer",
          required: true,
          nullable: false,
          doc: "Index of the refused plan action.",
          enum: nil,
          default: nil
        },
        %{
          name: "action",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "Name of the refused action.",
          enum: nil,
          default: nil
        },
        %{
          name: "unmet",
          order: 3,
          type: "list<string>",
          required: true,
          nullable: false,
          doc: "Unmet precondition atoms.",
          enum: nil,
          default: nil
        },
        %{
          name: "violated_absent",
          order: 4,
          type: "list<string>",
          required: true,
          nullable: false,
          doc: "Atoms that were required absent but present.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "ReceiptRequired",
      order: 4,
      kind: "EngineRejected",
      fields: [
        %{
          name: "step",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Step name with no recorded receipt.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "ReceiptRefused",
      order: 5,
      kind: "EngineRejected",
      fields: [
        %{
          name: "step",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Step name whose receipt was refused.",
          enum: nil,
          default: nil
        },
        %{
          name: "reason",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "Refusal reason.",
          enum: ["unattested", "bad_signature", "untrusted_key"],
          default: nil
        }
      ]
    },
    %{
      code: "LeaseRefused",
      order: 6,
      kind: "EngineRejected",
      fields: [
        %{
          name: "reason",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Refusal reason.",
          enum: ["expired", "out_of_scope", "ceiling", "bad_signature", "untrusted_key", "clock_skew"],
          default: nil
        },
        %{
          name: "lease_id",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "Id of the refused lease.",
          enum: nil,
          default: nil
        },
        %{
          name: "step",
          order: 3,
          type: "string",
          required: true,
          nullable: false,
          doc: "Step that was refused.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "NotAdmitted",
      order: 7,
      kind: "EngineRejected",
      fields: [
        %{
          name: "violations",
          order: 1,
          type: "list<object>",
          required: true,
          nullable: false,
          doc: "SHACL violations: {focus, path, component, message, severity}.",
          enum: nil,
          default: nil
        }
      ]
    },
    %{
      code: "UnverifiedLeaseRefused",
      order: 8,
      kind: "Unsupported",
      fields: [
      ]
    },
    %{
      code: "PolicyRefused",
      order: 9,
      kind: "EngineRejected",
      fields: [
        %{
          name: "policy_kind",
          order: 1,
          type: "string",
          required: true,
          nullable: false,
          doc: "Policy refusal kind.",
          enum: ["MissingEntry", "InventedOutcome", "BadMass", "DeadEnd", "Malformed"],
          default: nil
        },
        %{
          name: "state",
          order: 2,
          type: "string",
          required: true,
          nullable: false,
          doc: "State at which the policy was refused.",
          enum: nil,
          default: nil
        },
        %{
          name: "action",
          order: 3,
          type: "string",
          required: true,
          nullable: false,
          doc: "Action at which the policy was refused.",
          enum: nil,
          default: nil
        }
      ]
    }
  ]

  @vocabulary %{
    "engines" => ["PurRdf", "Eyeron"],
    "lease_ceilings" => ["observe", "select", "construct"],
    "lease_reasons" => ["expired", "out_of_scope", "ceiling", "bad_signature", "untrusted_key", "clock_skew"],
    "policy_refusal_kinds" => ["MissingEntry", "InventedOutcome", "BadMass", "DeadEnd", "Malformed"],
    "receipt_reasons" => ["unattested", "bad_signature", "untrusted_key"],
    "refusal_kinds" => ["NotSemanticContent", "Ambiguous", "EngineRejected", "Unsupported", "ResourceLimit"],
    "regimes" => ["simple", "rdf", "rdfs", "owl-rl", "d"]
  }

  @limits %{
    max_atoms_per_field: 10000,
    max_json_depth: 64,
    max_plan_actions: 1000,
    max_policy_entries: 100000,
    max_request_bytes: 16777216,
    n3_max_iterations: 4000
  }

  @doc "The registry schema id, for example `\"graphlaw.capability-registry/1\"`."
  @spec schema() :: String.t()
  def schema, do: @schema

  @doc "The GraphLaw release the registry was generated from."
  @spec graphlaw_version() :: String.t()
  def graphlaw_version, do: @graphlaw_version

  @doc "The GraphLaw ABI version the registry describes."
  @spec abi_version() :: pos_integer()
  def abi_version, do: @abi_version

  @doc "The registry digest literal (`\"sha256:<hex>\"`), the registry's own `registry_sha256`."
  @spec digest() :: String.t()
  def digest, do: @digest

  @doc "The surface digest literal (`\"sha256:<hex>\"`) over ABI version, op names and dialect names."
  @spec surface_digest() :: String.t()
  def surface_digest, do: @surface_digest

  @doc "Wire operation names in registry order."
  @spec names() :: [String.t()]
  def names, do: @names

  @doc "All operations in registry order."
  @spec ops() :: [op()]
  def ops, do: @ops

  @doc "The operation named `name`, or `:error` when the registry has no such operation."
  @spec op(String.t()) :: {:ok, op()} | :error
  def op(name) when is_binary(name), do: Map.fetch(@ops_by_name, name)
  def op(_name), do: :error

  @doc "The typed capability module for the operation named `name`, or `:error`."
  @spec module_for(String.t()) :: {:ok, module()} | :error
  def module_for("capabilities"), do: {:ok, AshGraphLaw.Capability.Capabilities}
  def module_for("sniff"), do: {:ok, AshGraphLaw.Capability.Sniff}
  def module_for("parse"), do: {:ok, AshGraphLaw.Capability.Parse}
  def module_for("convert"), do: {:ok, AshGraphLaw.Capability.Convert}
  def module_for("canonical"), do: {:ok, AshGraphLaw.Capability.Canonical}
  def module_for("sparql"), do: {:ok, AshGraphLaw.Capability.Sparql}
  def module_for("shacl"), do: {:ok, AshGraphLaw.Capability.Shacl}
  def module_for("shex"), do: {:ok, AshGraphLaw.Capability.Shex}
  def module_for("n3"), do: {:ok, AshGraphLaw.Capability.N3}
  def module_for("entail"), do: {:ok, AshGraphLaw.Capability.Entail}
  def module_for("datalog"), do: {:ok, AshGraphLaw.Capability.Datalog}
  def module_for("hooks"), do: {:ok, AshGraphLaw.Capability.Hooks}
  def module_for("law"), do: {:ok, AshGraphLaw.Capability.Law}
  def module_for("policy"), do: {:ok, AshGraphLaw.Capability.Policy}
  def module_for(_name), do: :error

  @doc "All dialects in global order (RDF dialects first, then the others)."
  @spec dialects() :: [dialect()]
  def dialects, do: @dialects

  @doc "RDF dialect names in registry order."
  @spec rdf_dialects() :: [String.t()]
  def rdf_dialects, do: for(d <- @dialects, d.kind == "rdf", do: d.name)

  @doc "Non-RDF dialect names in registry order."
  @spec other_dialects() :: [String.t()]
  def other_dialects, do: for(d <- @dialects, d.kind == "other", do: d.name)

  @doc "The steps of the `law` operation in registry order, keyed by wire name (`\"record-receipts\"`)."
  @spec law_steps() :: [law_step()]
  def law_steps, do: @law_steps

  @doc "The engine refusal detail codes (`details.code` wire values) in registry order."
  @spec refusal_codes() :: [refusal_code()]
  def refusal_codes, do: @refusal_codes

  @doc "The engine resource limits as an atom-keyed map."
  @spec limits() :: %{optional(atom()) => non_neg_integer()}
  def limits, do: @limits

  @doc "A closed registry vocabulary by name (`\"regimes\"`, `\"engines\"`, ...); `[]` when unknown."
  @spec vocabulary(String.t()) :: [String.t()]
  def vocabulary(name) when is_binary(name), do: Map.get(@vocabulary, name, [])

  @doc "The entailment regimes the `entail` operation accepts."
  @spec regimes() :: [String.t()]
  def regimes, do: vocabulary("regimes")

  @doc "The engines a `sniff` response may name."
  @spec engines() :: [String.t()]
  def engines, do: vocabulary("engines")

  @doc "The engine refusal kinds."
  @spec refusal_kinds() :: [String.t()]
  def refusal_kinds, do: vocabulary("refusal_kinds")

  @doc "The lease ceilings."
  @spec lease_ceilings() :: [String.t()]
  def lease_ceilings, do: vocabulary("lease_ceilings")

  @doc "The lease refusal reasons."
  @spec lease_reasons() :: [String.t()]
  def lease_reasons, do: vocabulary("lease_reasons")

  @doc "The receipt refusal reasons."
  @spec receipt_reasons() :: [String.t()]
  def receipt_reasons, do: vocabulary("receipt_reasons")

  @doc "The `policy` operation refusal kinds."
  @spec policy_refusal_kinds() :: [String.t()]
  def policy_refusal_kinds, do: vocabulary("policy_refusal_kinds")
end
