# SPDX-FileCopyrightText: 2026 ash_graphlaw contributors <https://github.com/seanchatmangpt/ash_graphlaw/graphs/contributors>
#
# SPDX-License-Identifier: MIT
# GENERATED by ggen from ontology.ttl (graphlaw-ash-capability-pack, graphlaw capability registry). DO NOT EDIT.

defmodule AshGraphLaw.Capability.Shex do
  @moduledoc ~S"""
  Typed `shex` capability (registry order 8).

  Validate a dataset against a ShEx schema and shape map.

  Request fields, response variants and the refusal vocabulary of this operation are declared in
  the GraphLaw capability registry and projected here without per-operation hand-written code.
  `run/2` builds the request, calls the real engine through `AshGraphLaw.call/2` (same options as
  `call/2`: server, timeouts, fuel) and decodes the response into
  `AshGraphLaw.Result.Shex`.

  ## Example

      {:ok, request} = AshGraphLaw.Capability.Shex.build_request([data: "...", schema: "...", map: "..."])
      request["op"]
      #=> "shex"

  See `AshGraphLaw.Capability.Registry.op/1` for the full field, variant and refusal metadata.
  """

  @behaviour AshGraphLaw.Capability

  alias AshGraphLaw.Capability.Coerce
  alias AshGraphLaw.Capability.Decode
  alias AshGraphLaw.Refusal
  alias AshGraphLaw.Telemetry

  alias AshGraphLaw.Result.Shex, as: Result

  @op "shex"

  @request_fields [
    %{
      name: "data",
      order: 1,
      type: "data_spec",
      required: true,
      nullable: false,
      doc: "Data to operate on: an object {text, dialect?, hint?, base?}; the dialect is sniffed when omitted.",
      enum: nil,
      default: nil
    },
    %{
      name: "schema",
      order: 2,
      type: "string",
      required: true,
      nullable: false,
      doc: "ShEx schema text.",
      enum: nil,
      default: nil
    },
    %{
      name: "schema_dialect",
      order: 3,
      type: "string",
      required: false,
      nullable: true,
      doc: "Schema syntax.",
      enum: ["shexc", "shexj"],
      default: "shexc"
    },
    %{
      name: "map",
      order: 4,
      type: "string",
      required: true,
      nullable: false,
      doc: "Shape map text.",
      enum: nil,
      default: nil
    },
    %{
      name: "base",
      order: 5,
      type: "string",
      required: false,
      nullable: true,
      doc: "Base IRI.",
      enum: nil,
      default: nil
    }
  ]

  @response_fields [
    %{
      name: "conforms",
      order: 1,
      type: "boolean",
      required: true,
      nullable: false,
      doc: "True when every map entry is conformant.",
      enum: nil,
      default: nil
    },
    %{
      name: "entries",
      order: 2,
      type: "list<object>",
      required: true,
      nullable: false,
      doc: "Shape map entries: {node, shape, status, reason}.",
      enum: nil,
      default: nil
    }
  ]

  @typedoc "The decoded result of a successful `shex` call."
  @type t :: Result.t()

  @doc "The wire name of the operation."
  @impl true
  @spec op() :: String.t()
  def op, do: @op

  @doc """
  The registry fields of this operation: `:request` for the request fields, `:response` for the
  union of the response fields of all variants (first-seen order, no enum lists).
  """
  @spec fields(:request | :response) :: [AshGraphLaw.Capability.Registry.field()]
  def fields(:request), do: @request_fields
  def fields(:response), do: @response_fields

  @doc """
  Builds the engine request for this operation from `args` (a keyword list or map).

  Refuses with `:invalid_capability_request` on unknown keys, missing required fields or type
  mismatches. Enum lists are informational and never enforced. The `"op"` key is injected here.
  """
  @impl true
  @spec build_request(AshGraphLaw.Capability.args()) :: {:ok, map()} | {:error, Refusal.t()}
  def build_request(args) do
    with {:ok, request} <- Coerce.request(@op, @request_fields, args) do
      {:ok, Map.put(request, "op", @op)}
    end
  end

  @doc """
  Decodes an engine response for this operation into its result struct. Never raises on
  unexpected shapes; a non-map response refuses with `:capability_response_undecodable`.
  """
  @impl true
  @spec decode(term()) :: {:ok, t()} | {:error, Refusal.t()}
  def decode(response) do
    with {:ok, map} <- Decode.ensure_map(response) do
      {:ok, Result.from_map(map)}
    end
  end

  @doc """
  Builds the request, runs it on the engine and decodes the response inside a
  `[:ash_graphlaw, :capability, ...]` telemetry span. `opts` are the options of `AshGraphLaw.call/2`.
  """
  @impl true
  @spec run(AshGraphLaw.Capability.args(), keyword()) :: {:ok, t()} | {:error, Refusal.t()}
  def run(args, opts \\ []) do
    Telemetry.capability(@op, opts, fn ->
      with {:ok, request} <- build_request(args),
           {:ok, response} <- AshGraphLaw.call(request, opts) do
        decode(response)
      end
    end)
  end
end
